.template_version
Gemfile
Gemfile.lock
source/javascripts/modules/anchored-headings.js
source/javascripts/modules/in-page-navigation.js
source/stylesheets/modules/_anchored-heading.scss
source/stylesheets/modules/_technical-documentation.scss

- Fix a Javascript error on mobile
- Remove extra padding from multi line code blocks
- Remove text from anchor links that’s appearing in Google search results
- Add a .template_version file which should make future updates easier

Update to latest version of the template

---

source/documentation/deploying_services/postgres.md

Made some changes to the language and punctuation suggested by @jollery in #24 - they weren't relevant there and didn't get merged, but didn't want to lose them.
- Check that the wording makes sense
- Ensure that the content looks correct in our docs template
Anyone but @bleach

Stylistic fixes on restore from snapshot docs

---

README.md

The build pipeline URL has changed so we need to update it in the README.
Sanity check.
Not @combor

Fix dead URL

---

source/documentation/deploying_apps/deploying_docker_image.md
source/index.html.md.erb

[Turn on Docker support as experimental](https://www.pivotaltracker.com/n/projects/1275640/stories/140834345)
Add documentation about the feature. Mention limitations.
Proofread. Check if formatting and formulations make sense. Check if documentation is complete (e.g. you think it should contain something more) or if instead some parts should be removed.
not @mtekel

Document docker image deployment support

---

source/documentation/getting_started/limitations.md

We started using this for deploying our own apps and are happy with it, so
make a more confident recommendation.
And fix an unordered list in the same section.
1. Check that the words make sense
1. Run the server as described in the README and verify that http://127.0.0.1:4567/#custom-domains-require-cdn renders correctly
Anyone.

[#124843741] Recommend cf-blue-green-deploy plugin

---

source/documentation/deploying_services/database_services.md
source/documentation/deploying_services/index.md
source/index.html.md.erb

This branch needs rebasing after https://github.com/alphagov/paas-tech-docs/pull/46 is merged. Added in information on self-signed certificates for MongoDB.
Read and check it is accurately described.
Dan Carley.

MongoDB Beta Documentation

---

source/documentation/deploying_apps/buildpacks.md

Now that the buildpack guidance markdown file is live, I've added an internal link to it in this section.
Please check the link works.
Anyone who is not Jon Glassman

Add link to buildpack guidance

---

source/documentation/deploying_services/use_a_custom_domain.md

Instructions on configuring CDN header forwarding.
Review in conjuction with the pull request to add this functionality on the paas-cdn-broker repository (hasn't been raised yet).
Proofread. Check the links work. See the repo's README for running instructions.
Anyone but me or @46bit

[#146274197] Instructions on configuring CDN header forwarding

---

source/documentation/deploying_apps/deploying_java.md
source/index.html.md.erb

Created Deploying Java apps section as part of https://www.pivotaltracker.com/story/show/148003307. This details:
- The minimum steps required to set up a simple "Hello World" Java app without using JVM-based applications
- How to deploy a Java app using JVM-based applications
- Further information on deploying using a .war file and what to do if your application requires arguments to start
Review text and ensure that it covers requirements in https://www.pivotaltracker.com/story/show/148003307.
Anyone except @chrisfarms and @jonathanglassman

[#148003307] Deploying java

---

.github/PULL_REQUEST_TEMPLATE.md

State that you should preview the content locally to see if it renders
correctly and that you should check for broken links (while we continue to
use the single-page-format with anchor tags).
Check whether the changes make sense and add value.
Anyone.

Make review steps more explicit in PR template

---

source/documentation/deploying_services/route_services.md

The non-production base domain name had been used here in error.
A simple code review is probably enough.
Not me.

[Support] Fix hostname in route-services docs.

---

source/documentation/troubleshooting/index.md

Added content for third party log management services, as per story https://www.pivotaltracker.com/story/show/150847208
1. Check that the content is accurate and the structure makes sense
1. Manually check the links work and are appropriate to the content
Any dev in PaaS team.

Third Party Log Management

---

source/documentation/using_ci/index.md

Removed a duplicate "should"
Code inspection is fine; you should should check that the only change is to remove  the duplicate.
If you wanted to be thorough you could could:
1. …
Anyone but @bleach

Remove duplicate "should"

---

source/documentation/deploying_apps/deploying_static_sites.md
source/documentation/deploying_apps/index.md

As we have recently implemented a functionality that will redirect any
http traffic to https. It will also strip the URL path along with the
query parameters. We'd like to have few paragraphs in our docs to
explain that we're doing this and why.
- Check if the new content makes sense

[#139841751] Add redirection notice and justification

---

source/documentation/deploying_apps/deploying_rails.md
source/documentation/deploying_apps/deploying_static_sites.md
source/documentation/deploying_apps/index.md
source/documentation/deploying_apps/orgs_spaces_targets.md
source/documentation/deploying_apps/production_checklist.md
source/documentation/getting_started/before_you_start.md
source/documentation/managing_apps/quotas.md
source/documentation/overview/benefits.md

Made changes to multiple sections in tech docs:
- Benefits
- PaaS Requirements
- Updated production checklist
- Added in references to production checklist and scaling sections
- Added content on sandbox targeting
1. Check that the changes in googledoc https://docs.google.com/document/d/14zwZzwJdqktKSu7-tiauqTcu6eTy29bjVucNTn9dLxk/edit?ts=5a018275# are reflected in PR
Anyone but Jon Glassman

Nips tucks

---

source/documentation/deploying_services/database_services.md
source/documentation/deploying_services/index.md
source/documentation/overview/benefits.md

Added Redis and Elasticsearch to list of available backing services. 
1. Check that the content is consistent with the story https://www.pivotaltracker.com/story/show/152231079 and the google doc https://docs.google.com/document/d/1EbuS_nWhj9PLPJ7EKGjxbooms39x7j9j_YDFtvYD0kY/edit
Anyone but me or @samcrang 
Please squash the commits

[#152231079] Add new backing services

---

source/documentation/deploying_apps/buildpacks.md
source/documentation/deploying_apps/deploying_docker_image.md
source/documentation/guidance/buildpacks.md
source/documentation/overview/benefits.md

We've added support for private Docker registries—this documents it
- read it, make sure it makes sense
- compare it to the Google doc linked to in the PT story
Anyone but @samcrang or @jonathanglassman 
Squash commits where it makes sense to keep commit history clean

[#152241791] Add documentation for private Docker

---

source/documentation/deploying_apps/production_checklist.md

add healthcheck to checklist. 
I think this is important as without one you risk putting or leaving an unhealthy instance in service.

add healthcheck to checklist

---

source/documentation/managing_users/user_accounts.md
source/documentation/monitoring_apps/metrics.md

"Exporting metrics data" changed to "Metrics" as per feedback from Michael Mokyrz. This makes it consistent with Logs.
1. Review title to make sure it makes sense.
Recommend @46bit or @samcrang.

Metrics section title change

---

source/documentation/deploying_apps/buildpacks.md
source/documentation/deploying_services/index.md
source/documentation/deploying_services/route_services.md
source/documentation/deploying_services/use_a_custom_domain.md
source/documentation/guidance/buildpacks.md
source/documentation/monitoring_apps/index.md
source/documentation/monitoring_apps/logs.md
source/documentation/using_ci/travis.md

Corrected and updated capitalisation of titles and some terms in the tech docs for consistency, and adherence to the style guide.
1. Check if any titles are still in upper case rather than normal case
Anyone excluding Jon Glassman.

Capitalisation corrections

---

nginx.conf

This commit updates the techdocs to use the system domain. It was missed during the moving to the system domain work.
Code review
Not @LeePorte

Update host redirect to point to primary domain

---

source/documentation/deploying_apps/deploying_node_js.md

Driven by story: https://www.pivotaltracker.com/story/show/153602295
Changes to PostgreSQL setup with Node.js:
- Corrected "mypostgres" to "SERVICE-NAME" in both code and paragraph below to ensure consistency
- Changed content to be more direct to user
- Added in two links to cf env resources
- Removed superfluous backticks in code at end of section
1. Check that content addresses story requirements

Correction to postgre sql setup with node

---

source/documentation/deploying_services/database_services.md
source/documentation/guidance/plugins.md
source/documentation/troubleshooting/ssh.md
source/index.html.md.erb

We are pointing users towards our cf-conduit plugin to help with tunneling to backing services
* Ensure renders ok
* Check links etc
Not @chrisfarms nor @jonathanglassman

[#153995238] Add Conduit docs

---

source/documentation/guidance/pentest.md

This question didn't parse correctly.
1. …
Not me

[Support] Fix grammar in pentest docs.

---

source/documentation/deploying_services/configure_cdn.md
source/documentation/deploying_services/use_a_custom_domain.md
source/index.html.md.erb

Created section describing how to set up a custom domain without using the `cdn-route` service.
1. Review the content to ensure that it fulfills the requirements of https://www.pivotaltracker.com/story/show/136197593
Anyone except @46bit or me.

Configure your own CDN

---

source/documentation/getting_started/privacy.md

- There were multiple options for what to do, either removing "to" or adding "store". I went with the latter as it made more sense with "on servers outside". I'm happy to be corrected though!
- My text editor also added a trailing new line to the end of the file.

Add a missing word in privacy.md

---

source/documentation/deploying_apps/deploying_docker_image.md

Added content to manage user expectations when the docker registry that supports their app is offline. Part of story https://www.pivotaltracker.com/story/show/154518930.
1. Check that the content covers the story requirements.
Anyone except Jon Glassman or Sam Crang

[#154518930] Docker registry offline

---

source/documentation/deploying_apps/deploying_docker_image.md

Updated sub-section title from "Offline Docker registry" to "Docker Registry Availability Requirements" in line with Approval feedback.
1. Check the title is in line with what was agreed.

Docker Registry Availability Requirements

---

source/documentation/deploying_services/index.md

Created and expanded Redis backing service content:
- Set up a Redis service
- Bind a Redis service to your app
- Unbind a Redis service from your app
- Delete a Redis service
- Redis maintenance & backups
- Further information
Part of https://www.pivotaltracker.com/story/show/154638143
1. Check that content fulfills requirements of story https://www.pivotaltracker.com/story/show/154638143
Anyone except Jon Glassman or Andrew Bruce

Create redis section

---

source/documentation/deploying_services/index.md

- Added content on how to import and export bulk data to and from PostgreSQL and MySQL databases
- Added examples of VCAP_SERVICES environment variables
This is to address https://www.pivotaltracker.com/story/show/154926642
1. Check the content addresses the story
Anyone except Jon Glassman or Andrew Bruce

Expand postgresql & mysql doc sections

---

source/documentation/deploying_services/index.md

Added content on Redis clustered and unclustered plans, with links for further information.
1. Check that the content addresses the requirements of https://www.pivotaltracker.com/story/show/156123651.

Add Redis plans section

---

source/documentation/deploying_apps/stopping_and_deleting_apps.md

Reverts alphagov/paas-tech-docs#127
It require 2nd phase of review.

Revert "Correct deleting services section"

---

source/documentation/managing_apps/restarts.md
source/index.html.md.erb

- Created restarts markdown file with content on CF restarting apps outside of your direct control.
- Added new restarts file into index file.
1. Check this fulfils requirements of story: https://www.pivotaltracker.com/story/show/155904229
Anyone except Jon Glassman or Sam Crang

Add Restarts section in Managing Apps section

---

source/documentation/managing_apps/restarts.md

What
----
Updated 1st link as previous link is for different audience.
How to review
-------------
Who can review
--------------

Update 1st link

---

source/documentation/getting_started/passwords.md

What
----
We now set the expiry CF CLI sessions to 20 hours.
How to review
-------------
1. …
Who can review
--------------
Anyone but me

[#157189960] Update session expiry guidance

---

config/tech-docs.yml

What
----
Update header menu to reflect header menu on product pages
How to review
-------------
1. Check that the tech docs header is now identical to the product page header
Who can review
--------------
Anyone

Update header menu

---

source/documentation/index.md
source/documentation/orgs_spaces_users/index.md

What
----
- Added content summarising what the PaaS admin tool is
- Added PaaS admin tool content into the orgs, spaces and users section
- Made minor content corrections and added cross-references
How to review
-------------
1. Check it fulfils story requirements: https://www.pivotaltracker.com/story/show/158219851
Who can review
--------------
Anyone except Lee Porte or Jon Glassman

Add admin tool

---

source/documentation/index.md
source/documentation/orgs_spaces_users/index.md

What
----
- Clarified admin tool permissions for different roles.
- Added in org auditor role.
How to review
-------------
1. Check the permissions for the admin tool are represented correctly.
Who can review
--------------
@paroxp

Admin tool permissions

---

source/documentation/orgs_spaces_users/index.md

What
----
Changed content so that it is clear that, under "Remove users from an org", you can remove a user directly by selecting "Remove user from organisation"
How to review
-------------
1. Check it addresses comments in the story: https://www.pivotaltracker.com/story/show/158219851
Who can review
--------------
@chrisfarms

Remove from org button

---

source/documentation/using_ci/index.md
source/documentation/using_ci/jenkins.md

What
----
- Fixed broken link in `Choose CI tool` section
- Removed html comments and replaced with #  
- Added in ```bash to start of code block
How to review
-------------
1. Check it fixes issues identified in approval step of https://www.pivotaltracker.com/story/show/158791278
Who can review
--------------
Jonathan Matthews

Travis ci update post approval

---

source/documentation/orgs_spaces_users/index.md

What
----
- Changed content to reflect updated admin tool user journeys.
- Minor edits of content to bring in line with style
- Added new section on viewing bills
How to review
-------------
1. Check that it covers story: https://www.pivotaltracker.com/story/show/159073908
Who can review
--------------
Anyone except Jon Glassman or Rafal Proszowski.

Updated admin tool content

---

source/documentation/deploying_services/index.md

What
----
Expanded Elasticsearch section within Deploying Backing Services section of tech docs. This is an MVP and has spun off multiple other stories for investigation.
How to review
-------------
1. Check that the content fulfils story https://www.pivotaltracker.com/story/show/154638140
Who can review
--------------
Anyone except Jon Glassman or Jonathan Matthews.

Elasticsearch

---

source/documentation/orgs_spaces_users/index.md

What
----
Clarified certain terms, added links, and tidied up the text.
How to review
-------------
Who can review
--------------
N/A as minor changes

Admin tool minor updates post 2i

---

source/documentation/deploying_services/index.md

What
----
Post 2i tweaks to content created for https://www.pivotaltracker.com/story/show/159563732
How to review
-------------
1. Check content still fulfils requirements of https://www.pivotaltracker.com/story/show/159563732
Who can review
--------------

Encryption type - Post 2i tweaks

---

source/documentation/deploying_services/index.md

What
----
Added Elasticsearch backups content as previous content was inaccurate.
How to review
-------------
1. Check it fulfils https://www.pivotaltracker.com/story/show/160202537
Who can review
--------------
Anyone excluding Jon Glassman or Lee Porte

Add Elasticsearch backups

---

source/documentation/monitoring_apps/metrics.md

What
----
- Added Prometheus metrics to Metrics section 
- Minor tweaks to Metrics Exporter app section
- Minor tweaks to Metrics section to reflect two methods
How to review
-------------
1. Check it fulfils https://www.pivotaltracker.com/story/show/159077375
Who can review
--------------
Anyone except Jon Glassman or Rafal Proszowski

Add Prometheus metrics to Metrics section

---

source/documentation/monitoring_apps/metrics.md

Reverts alphagov/paas-tech-docs#171
This needs to go through 2i

Revert "Add Prometheus metrics to Metrics section"

---

source/documentation/getting_started/before_you_start.md
source/documentation/guidance/buildpacks.md
source/documentation/overview/benefits.md

What
----
Tech docs story for https://github.com/alphagov/paas-cf/pull/1547
How to review
-------------
Code review
Who can review
--------------
Not me

[#160582942] update docs to enable dot net

---

source/documentation/monitoring_apps/metrics.md

```
Revert "Revert "Add Prometheus metrics to Metrics section""
Reverts alphagov/paas-tech-docs#173
```
#173 is a revert PR because it hasn't gone through tech writer 2i.
Once 2i is happy this can be merged.

[#159077375] Tech docs prometheus metrics

---

source/documentation/monitoring_apps/logs.md

What
----
Bring Log section in line with style:
- Remove passive voice
- Remove unnecessary or duplicated content
- Remove words to avoid
- Fix formatting
- improve flow of information
How to review
-------------
1. Check no instructions have been lost or misinterpreted and that it fulfils https://www.pivotaltracker.com/story/show/161111049
Who can review
--------------
that can't review, …

Bring Logs section in line with GDS style

---

source/documentation/deploying_services/elasticsearch.md
source/documentation/deploying_services/redis.md
source/documentation/deploying_services/use_a_custom_domain.md

What
----
Add html to fix bugged table. 
How to review
-------------
1. Check tables are fixed
Who can review
--------------

Fix bugged table

---

source/documentation/deploying_apps/buildpacks.md
source/documentation/guidance/architecture.md

What
----
Fix table error caused by tech doc tool bug
How to review
-------------
Who can review
--------------

Fix tables

---

source/documentation/deploying_services/use_a_custom_domain.md

What
----
Implemented changes from 2i review of custom domains content.
How to review
-------------
1. Check no bugs have crept in and it still fulfills story: https://www.pivotaltracker.com/story/show/161837922
Who can review
--------------

Custom Domain post-2i changes

---

source/documentation/deploying_services/configure_cdn.md
source/documentation/deploying_services/elasticsearch.md
source/documentation/deploying_services/mysql.md
source/documentation/deploying_services/postgresql.md
source/documentation/deploying_services/redis.md
source/documentation/deploying_services/route_services.md
source/documentation/deploying_services/use_a_custom_domain.md

What
----
Add in missing H2s to ensure backing service section complies with accessibility requirements.
How to review
-------------
1. Check content complies with https://www.pivotaltracker.com/story/show/163301573
Who can review
--------------
Anyone excluding Jon Glassman

Accessibility headers

---

source/documentation/deploying_services/redis.md

What
----
Updated Redis plans content to reflect new plan structure.
How to review
-------------
1. Check that it fulfils https://www.pivotaltracker.com/story/show/163396384
Who can review
--------------
Alex Tomlins for pairing review.

Update Redis plans content

---

Gemfile
Gemfile.lock

Reverts alphagov/paas-tech-docs#197
Reverting because the build is failing.

Revert "Update docs to use tec docs gems v1.8.0"

---

README.md

What
----
Resolves #143
How to review
-------------
1. Check it isn't in the readme anymore
Who can review
--------------
Anyone

Remove warning about editing files from README

---

source/deploying_services/s3/index.html.md.erb
source/documentation/deploying_services/index.md
source/documentation/deploying_services/s3.md

What
----
Created Amazon S3 broker backing service content.
How to review
-------------
1. Check it fulfils story: https://www.pivotaltracker.com/story/show/165348640
Who can review
--------------

Create Amazon S3 broker content

---

source/documentation/guidance/pentest.md

What
----
Changed "Is is" to "It is"
How to review
-------------
Who can review
--------------

Correct typo

---

source/documentation/getting_started/get_started.md

What
----
Added in sign in instructions for single sign on capability.
How to review
-------------
1. Check that it fulfils https://www.pivotaltracker.com/story/show/166079453
Who can review
--------------
Anyone except Jon Glassman or Toby LWR

Create single sign on instructions

---

source/documentation/getting_started/get_started.md

What
----
George Lund at GDS spotted our tech docs advice and the advice in our emails were mismatched. This commit fixes that.
How to review
-------------
1. Read the words
Who can review
--------------
Anyone

Correct advice on enabling SSO to say GDS users can self-serve

---

config/tech-docs.yml

What
----
Removing the phase from the header brings consistency with the header on the product pages.
How to review
-------------
Who can review
--------------
Anyone

Remove the phase from the header

---

source/documentation/managing_apps/scaling.md

What
----
Describe what you have changed and why.
How to review
-------------
1. …
Who can review
--------------

Changes post 2i

---

source/documentation/deploying_apps/deploying_docker_image.md

What
----
Docker is no longer experimental
How to review
-------------
Who can review
--------------

Remove experimental text from Docker section

---

source/documentation/index.md

What
----
GOV.UK PaaS is in beta, not private beta.
How to review
-------------
Who can review
--------------

Change "private beta" to "beta"

---

source/documentation/guidance/buildpacks.md

What
----
Removed experimental.
How to review
-------------
Who can review
--------------

Remove experimental

---

source/documentation/deploying_services/s3.md

What
----
Added content on how to access the Amazon S3 bucket from outside of the GOV.UK PaaS.
How to review
-------------
1. Check it fulfils the https://www.pivotaltracker.com/story/show/166837820 story.
Who can review
--------------
Anyone except Jon Glassman or Tom Whitwell.

Amazon S3 bucket external access

---

source/documentation/managing_apps/scaling.md

What
----
Corrected link error.
How to review
-------------
1. …
Who can review
--------------

Correct link error

---

source/documentation/managing_apps/quotas.md

What
----
Explains in the docs how to see all quotas
How to review
-------------
1. Copy review
Who can review
--------------
Anyone

[#167565124] Explain how to see all quotas on the platform

---

source/documentation/deploying_apps/index.erb
source/documentation/getting_started/get_started.md
source/documentation/troubleshooting/ssh.md

Reverts alphagov/paas-tech-docs#236
This erroneously overwrote some newer documentation, we will raise a new PR with just the desired changes

Revert "Add in Cloud Foundry v3 API"

---

source/documentation/deploying_apps/index.erb
source/documentation/getting_started/get_started.erb
source/documentation/troubleshooting/ssh.erb

What
----
In this pull request https://github.com/alphagov/paas-tech-docs/pull/236
we added new documentation about the V3 API, but this PR also included
some single sign-on content (from #234) that has since been overwritten
This commit recommits the content which we care about.
Who can review
--------------
Done as pair with @jonathanglassman

Partially recommit changes from #236

---

source/documentation/deploying_services/s3.md

What
----
Documents what kind of encryption the S3 broker uses. It was not in our documentation, and tenants had asked about it.
How to review
-------------
1. Check it fulfils https://www.pivotaltracker.com/story/show/167756968
Who can review
--------------

Add s3 bucket encryption

---

source/documentation/deploying_services/use_a_custom_domain.erb

[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/167565279)
What
----
We updated the broker which is now different and more configurable
How to review
-------------
Who can review
--------------
Not @tlwr

Add information about configuring cdn default ttl

---

source/documentation/deploying_apps/production_checklist.md

What
----
Re-write and update production checklist content based on output from doc-a-thon.
How to review
-------------
1. Check new content fulfils https://www.pivotaltracker.com/story/show/167640772
Who can review
--------------
Anyone except @jonathanglassman and @AP-Hunt

Re-write production checklist

---

source/documentation/deploying_apps/production_checklist.md

Reverts alphagov/paas-tech-docs#247
I forgot about 2️⃣ 👁

Revert "Re-write production checklist"

---

source/deploying_apps.html.md.erb
source/documentation/deploying_apps/production_checklist.md

Reverts alphagov/paas-tech-docs#251
This needs a review by 2️⃣ 👁

Revert "Revert "Re-write production checklist""

---

source/documentation/deploying_apps/index.erb

What
----
Updated the deploying private apps section in line with the doc-a-thon feedback.
How to review
-------------
1. Check that it fulfils story https://www.pivotaltracker.com/story/show/167640865
Who can review
--------------
Anyone except Jon Glassman or Andy Hunt

Deploying private apps section update

---

source/documentation/deploying_apps/deploying_rails.md
source/documentation/deploying_apps/index.erb
source/documentation/getting_started/get_started.erb
source/documentation/managing_apps/scaling.md

What
----
Updated links to production checklist. This section is now called "Deploy an app to production".
How to review
-------------
1. Check it fulfils https://www.pivotaltracker.com/story/show/167640772
Who can review
--------------

Change links for production checklist

---

source/documentation/deploying_services/s3.md

What
----
Follow-up to #248 
Markdown formatting got a bit mangled when rendered by app, this PR fixes it.
How to review
-------------
Check formatting looks correct when rendered by middleman app. e.g.
Who can review
--------------
Anyone but me

fix formatting after #248

---

source/documentation/managing_apps/ssh.erb

What
----
Amended content in line with Doc-a-thon feedback.
How to review
-------------
1. Check it fulfils https://www.pivotaltracker.com/story/show/167626104
Who can review
--------------
Anyone but Jon Glassman and Andy Hunt

Connecting using SSH

---

source/documentation/deploying_services/use_a_custom_domain.erb

What
----
Fix the link
How to review
-------------
1. Check the link is correct now
Who can review
--------------

Fix broken link to "## How custom domains work"

---

source/documentation/deploying_apps/production_checklist.md
source/documentation/getting_started/get_started.erb

What
----
Added in information about trial and paid accounts to the tech docs. Driven by the content audit.
How to review
-------------
1. Check it fulfils story https://www.pivotaltracker.com/story/show/168980837
Who can review
--------------
TBC

Add in trial and paid accounts to the tech docs

---

source/documentation/deploying_apps/index.erb
source/documentation/deploying_services/route_services.md

What
----
Fixed up content around route services, and X-Forwarded-For header for authentication.
More details in commit messages
How to review
-------------
Who can review
--------------
Done as pair with @jonathanglassman

Guidance around X-Forwarded-For header, IP safelisting, and route services

---

source/documentation/deploying_services/route_services.md

What
----
I moved the repo
How to review
-------------
1. …

Update link to ip auth route service

---

Gemfile.lock

What
----
Update tech docs to 2.0.7.
How to review
-------------
Who can review
--------------

Update tech docs to 2.0.7

---

source/documentation/managing_apps/quotas.md

What
----
Our documentation showed how to view the big table of all quotas, but not how
to view the details of a specific quota.
How to review
-------------
Who can review
--------------
Anyone

Document how to view a specific quota

---

source/deploying_services/influxdb/index.html.md.erb
source/documentation/deploying_services/index.md
source/documentation/deploying_services/influxdb.erb

[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/169061254)
What
----
We are releasing a private beta of InfluxDB
We should document for our users, how it works, and what features we've added to make it easier to use (e.g. Prometheus)
How to review
-------------
Who can review
--------------
Done as pair with @jonathanglassman 
Checklist
---

[#169061254] Add InfluxDB private beta documentation

---

source/documentation/deploying_services/influxdb.erb

the link was broken, this fixes it

fix typo in markdown syntax

---

source/documentation/deploying_services/mysql.md
source/documentation/deploying_services/postgresql.md
source/documentation/deploying_services/redis.md
source/documentation/monitoring_apps/metrics.md

What
----
Added backing service metrics content.
How to review
-------------
1. Check it fulfils story https://www.pivotaltracker.com/story/show/169430669
Who can review
--------------
Anyone except Andy Hunt and Jon Glassman

Add backing service metrics content

---

source/documentation/monitoring_apps/logs.md

For noobs like me who're not savvy with the commands
What
----
Describe what you have changed and why.
How to review
-------------
Check the words changed
Who can review
--------------
Technical writer?

Add note that cf restage causes downtime

---

source/documentation/deploying_services/use_a_custom_domain.erb

What
----
We're now Tech Docs trained. We agreed we'd revisit these docs after the training. This commit updates them to meet the areas of improvement I noticed after going through our checklist.
How to review
-------------
1. Check the changes look OK;
2. Try out the *Tech docs review checklist* yourself.
Who can review
--------------
Not @46bit

[#169872495] Update custom domain docs after Tech Docs training

---

source/deploying_services/influxdb/index.html.md.erb
source/documentation/deploying_services/index.md
source/documentation/deploying_services/influxdb.erb

[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/171539917)
What
----
Remove references to private beta
Update InfluxDB output to refer to correct `paid/free` status (`free`)
How to review
-------------
1. …
Who can review
--------------
@paroxp

[#171539917] InfluxDB is not in private beta

---

source/documentation/deploying_services/postgresql.md

[Story](https://www.pivotaltracker.com/story/show/172099629)
See story and associated PRs

[#172099629] Add RDS restore_from_latest_snapshot_before param

---

source/documentation/deploying_services/mysql.md
source/documentation/deploying_services/postgresql.md
source/documentation/monitoring_apps/metrics.md

What
----
Users can now access RDS Logs from within Pazmin
Let's document that
How to review
-------------
Read the words
Perhaps preview locally
Who can review
--------------
Not @tlwr

Add a short note for backing service logs

---

source/documentation/deploying_services/use_a_custom_domain.erb

What
----
I have updated the example outputs and corrected some DNS record types to reflect the changes in the CDN broker to reflect the records as ACM will expect.
I have also added in the 2i returned content on migrating. We can link to this from the emails that are going to be sent to tenants.
How to review
-------------
1. …
Who can review
--------------
Anyone

[#172893254] Acm all the certs

---

source/documentation/troubleshooting/password.md

[Story](https://www.pivotaltracker.com/story/show/170700038)
What
----
We now have a nice UX for doing password resets using Pazmin
We should point users to that instead of UAA
How to review
-------------
Check the links (contingent on the other PRs in the story)
Who can review
--------------
Not @tlwr

[#170700038] Update password reset links to point to pazmin

---

Dockerfile

What
----
Update Docker image to ruby 2.7 and python 3
How to review
-------------
1. …
Who can review
--------------

Update Docker image to ruby 2.7 and python 3

---

source/documentation/deploying_services/use_a_custom_domain.erb

What
----
Tenants were unclear on two points.
1. If they needed to perform any actions at all
2. Which domains they need to supply in the `cf update-service` call
This commit addresses both points
How to review
-------------
1. Copy review
Who can review
--------------
Anyone

Clarify ACM migration instructions

---

source/documentation/deploying_services/index.md

What
----
Inserted guidance on sharing service instances 
How to review
-------------
2. Confirm that this is the best place for this new content to sit
Who can review
--------------
Anyone on the team who knows about sharing service instances

Include guidance on sharing service instances

---

source/documentation/using_ci/travis.md

Fix minor capitalisation issues
What
----
Fix minor capitalisation issues to make content more accessible
How to review
-------------
Who can review
--------------
Jani

Fix capitalisation for accessibility

---

source/documentation/deploying_services/postgresql.md

Fix several capitalisation issues in body and link text
What
----
Fixed capitalisation issues to make text more readable
How to review
-------------
Who can review
--------------
Jani

Fix capitalisation issues for accessibility

---

source/documentation/managing_apps/ssh.erb

What
----
Fixed capitalisation in link for accessibility
How to review
-------------
Who can review
--------------
@kr8n3r

Fix capitalisation in link

---

source/documentation/monitoring_apps/metrics.md

What
----
Fixed capitalisation in linked text 
How to review
-------------
Who can review
--------------
@kr8n3r

Fix capitalisation in link text for accessibility

---

source/documentation/deploying_apps/deploying_java.md

What
----
Removed bold text used for emphasis to comply with accessibility regulations
How to review
-------------
Who can review
--------------
@kr8n3r

Remove bold text for emphasis

---

source/documentation/monitoring_apps/metrics.md

What
----
Updated link text for AWS regions
How to review
-------------
Who can review
--------------
@kr8n3r

Update link text for accessibility

---

source/documentation/monitoring_apps/logs.md

What
----
Fixed capitalisation in linked text for accessibility reasons
How to review
-------------
Who can review
--------------
@kr8n3r

Fix capitalisation in link text

---

source/documentation/orgs_spaces_users/index.md

What
----
Text description was missing a few things which are shown in the diagrams so have added them for accessibility reasons
How to review
-------------
2. Check that the new content is accurate
Who can review
--------------
@LeePorte

Update text to reflect info shown in diagrams

---

config/tech-docs.yml

What
----
Adds a link to the roadmap in the header
How to review
-------------
1. Check the link appears in the header and goes where you'd expect
Who can review
--------------
Anyone at all

Link to roadmap in the header

---

source/documentation/managing_apps/autoscaling.erb
source/managing_apps.html.md.erb

What
----
[Story](https://www.pivotaltracker.com/story/show/169974740)
Markdown kicked my ass
How to review
-------------
1. Do some autoscaling in [tlwr](https://admin.tlwr.dev.cloudpipeline.digital/)
Who can review
--------------
Not @tlwr

[#169974740] Document autoscaling apps

---

source/documentation/guidance/architecture.md

What
----
Looks like a typo, the copy makes it sound like the final sentence should be in the "Relevance to CloudFoundry" column
How to review
-------------
1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected. (I've checked it in the Github markdown viewer)
Who can review
--------------
Anyone on the documentation team

Move sentence to fill empty cell in table

---

source/documentation/deploying_services/postgresql.md

What
----
Added new instructions for how to bind apps with a read-only user
How to review
-------------
Who can review
--------------
@barsutka

Add info on binding your app with a read-only user

---

source/documentation/deploying_services/postgresql.md

What
----
**Before**
**After**
How to review
-------------
1. …
Who can review
--------------

fix indentation

---

source/documentation/deploying_services/elasticsearch.md

What
----
Refer to https://github.com/alphagov/paas-cf/pull/2436
How to review
-------------
Code review
1. …
Who can review
--------------
Not @tlwr

elasticsearch: use 7.x instead of 6.x

---

source/documentation/deploying_services/sqs.md

What
----
Fixed some typos and made some style changes in line with the style guide
How to review
-------------
2. Check that the content still makes sense from a technical perspective.
Who can review
--------------
Ideally @chrisfarms or anyone else who knows about this content

Fix typos and small style changes

---

source/documentation/deploying_apps/env_variables.md

What
----
remove a duplicated word
How to review
-------------
👀

remove duplicated word

---

source/documentation/deploying_services/postgresql.md.erb

What
----
https://github.com/alphagov/paas-cf/pull/2490
_Rendered_
How to review
-------------
1. …

postgres: update_minor_version_to_latest update

---

source/documentation/deploying_apps/index.erb

What
----
Fix broken link and add NCSC CSP link
How to review
-------------
1. …
Who can review
--------------

Fix broken link and add NCSC CSP link

---

source/documentation/monitoring_apps/logs.md

What
----
A tenant pointed out to us that the filters were wrong, and supplied a patch to fix them up.
How to review
-------------
1. Check the changes to the logstash filters make sense
Who can review
--------------
Dwayne Bailey and a PaaS team member

Update recommended Logstash filter configuration

---

source/documentation/deploying_services/postgresql.md.erb

What
----
In order to make upgrading a smoother process it makes sense to document
this in our tech docs rather than asking people to check for old emails.
It also makes sense to pull this up to an appropriate level so that it
is surfaces on the side menu.
How to review
-------------
1. Check the words added
Who can review
--------------
Probably @markpeterbuckley

Add information about upgrading from postgres 9.5

---

source/documentation/deploying_services/postgresql.md.erb

What
----
Update availability of `postgis` extension across Postgres versions~
How to review
-------------
Who can review
--------------
Anyone

[#172528011] Update Postgres 9.5 extensions

---

source/documentation/deploying_services/postgresql.md.erb

What
----
Made some changes so that content is in line with the style guide and is more readable
How to review
-------------
2. Check that the content still makes sense from a technical perspective.
Who can review
--------------
Not @cmcnallygds

Make style changes and improve clarity

---

source/documentation/index.md

What
----
We're no longer a beta service so we should state that we are live.
How to review
-------------
Who can review
--------------
Anyone

Update status to live

---

source/documentation/deploying_services/postgresql.md.erb

What
----
Makes Postgres upgrade docs consistent with reality 176574936. Also documents which extensions are available for Postgres 12.
How to review
-------------
1. Copy review

[#176574936] Make Postgres upgrade docs consistent with reality 

---

source/documentation/orgs_spaces_users/index.md

What
----
The suuport page link for signing up to a new org was out of date
How to review
-------------
Code review
Who can review
--------------
Anyone

Update support link to new support form

---

source/javascripts/cookies.js

What
----
Replace "PaaS" with "GOV.UK PaaS"
How to review
-------------
- review proposed word change
Who can review
--------------
anyone

Update cookie banner text

---

config.rb

Add security.txt to Middleman

---

source/documentation/guidance/plugins.md

What
----
Expanded the Conduit info into a full tutorial so that it's more helpful for users and added some other useful CF plugins.
How to review
-------------
2. Check that the content is accurate and complete.
Who can review
--------------
Not @cmcnallygds

Expand Conduit tutorial and add more plugins

---

source/documentation/deploying_services/elasticsearch.md
source/documentation/deploying_services/influxdb.erb

What
----
Added documentation for how to use the IP restriction feature for Aiven backing services
How to review
-------------
1. …
Who can review
--------------
@cmcnallygds

[#178656134] Aiven ip restrictions

---

Dockerfile

What
----
Tweak dockerfile to fix build process
How to review
-------------
1. Make sure it builds on CI
Who can review
--------------
Anyone

Tweak dockerfile to fix build process

---

Dockerfile
requirements.txt

What
----
Changed from Alpine to debian as the ruby base container as we were seeing issues with musl post Alpine 3.14
How to review
-------------
1. Check the tests pass
Who can review
--------------
Anyone

Unalpine docker

---

source/documentation/managing_apps/quotas.md

According to @markpeterbuckley on https://www.pivotaltracker.com/story/show/178896942
What
----
Added table of quotas so our tenants can plan their usage.
How to review
-------------
1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected with:
``` sh
$ bundle exec middleman server
```
Who can review
--------------
Non-Cornish PaaS devs

Add quota table

---

source/documentation/deploying_services/elasticsearch.md
source/documentation/deploying_services/opensearch.md

What
----
Documentation the migration path from Elasticsearch to OpenSearch
How to review
-------------
1. Did I get the migration details right?

[#180411083] Documentation the migration path from Elasticsearch to OpenSearch

---

source/documentation/deploying_services/s3.md

What
----
We deliberately don't give any usage examples here, because a useful example
would be using an AWS SDK for the user's programming language, and we don't
know what that is.
Instead, we suggest what they're good for and direct people to look at the relevant SDK.
How to review
-------------
1. Do you agree with the approach?

[#180331598] Flesh out our AWS Presigned URLs documentation

---

source/documentation/deploying_services/use_a_custom_domain.erb

What
----
Explains how to find out about TLS version and ciphers
How to review
-------------
1. Read and check that the new info makes sense
Who can review
--------------
Anyone

Explains how to check TLS version and ciphers

---

source/documentation/monitoring_apps/logs.md

Provide the user with the instructions on how to setup their own firewall groups with a link to further help and screenshots.
This is to make the user onboarding easier for the user
What
----
Describe what you have changed and why.
How to review
-------------
1. …
Who can review
--------------

Update how to apply firewall settings for Logit.io

---

source/billing_system.html.md.erb

What
----
As part of new billing we have generated some information on how it works.
How to review
-------------
Have a look at the changes and whether you think the information is in the right place - might be one for product pages?
1. …
Who can review
--------------

Add documentation of the billing system

---

source/documentation/index.md

What
----
Omit exact date as not known yet.
How to review
-------------
1. …
Who can review
--------------
not @kr8n3r

Decommission date

---

source/documentation/deploying_services/redis.md.erb

Add info for how to retrieve the maintenance windows for redis service instances.
1. Check the content is correct
Not me

[#183047939] Add maintenance window retrieval info for redis

---

source/documentation/deploying_services/postgresql.md.erb

What
----
Made changes as required by ticket 182452434.
How to review
-------------
Who can review
--------------
Anyone on the PaaS team.

[#182452434] Added info on postgres import errors

---

source/documentation/deploying_services/postgresql.md.erb

What
----
Changed postgres doc as required by [ticket](https://www.pivotaltracker.com/n/projects/1275640/stories/172582262).
How to review
-------------
1. …
Who can review
--------------
Preferably a tech writer.

[#172582262] Amended postgres doc

---

README.md

Description:
- Adds references to deployment to GitHub pages
What
----
Code review.

185550872 - Update README

---

source/documentation/deploying_services/s3.md

What
----
Update s3 bucket presigned url topic to include a line about using them outside the PaaS
How to review
-------------

Update s3 bucket presigned url topic

---

README.md

Description:
----
- Adds the right Markdown syntax for links

BAU - Fix broken links

---

source/documentation/deploying_services/postgresql.md.erb

What
----
Updating the docs to include additional migration advice
How to review
-------------
Follow the readme instruction to render the docs locally
Review the changed section(s)
Who can review
--------------
Any team member

added migration advice/detail

---

config/tech-docs.yml
source/documentation/index.md

What
----
- Added 'Decommissioned ' messaging
- Removed unnecessary content
How to review
-------------
Check the md files.
Who can review
--------------
People with powers

[186578173] check-post-decomission

---

.github/workflows/deploy.yml

Reverts alphagov/paas-tech-docs#555

Revert "github-action: bump actions/upload-pages-artifact from 2.0.0 to 3.0.0"

---

requirements.txt

What
----
Updated linkchecker to v10.5.0
How to review
-------------
2. Manually check that any removed or renamed anchor tags are not in use ([linkchecker](https://github.com/linkcheck/linkchecker) doesn't do this).
3. …
Who can review
--------------
GovPaaS

Updated linkchecker to v10.5.0
