source/documentation/deploying_services/index.md, source/documentation/deploying_services/postgres.md
Story #138344907 to document free plan and #137716243 to document encrypted plan. Descriptions below
#138344907
What
Document the existence of the Postgresql "free" plan.
Why
Because without authorisation this is the only plan people trying out the PaaS can use, and it is not clear that it exists in the documentation.
If we don't do this
We will continue to receive requests from trial tenants asking for their account to be upgraded when it doesn't need to be,
#137716243
What
Add documentation to the tenant manual about the new Postgres service plans which have "enc" in their name:
database storage is encrypted as rest (when the RDS instance is shutdown)
we recommend that you use it for production workloads
you cannot enable or disable encryption on an existing service
it is not compatible …
=> Postgres encryption and free plan

source/documentation/troubleshooting/ssh.md
Add workaround for setting up SSH environment correctly.
Story #138036037.
To test: check that the documentation now enables SSH sessions to work correctly. Check the command is accurate for all apps. Confirm that it needs to be run every time you SSH (as docs assume currently).
=> Document SSH environment fix

.gitignore, .travis.yml, Gemfile, Gemfile.lock, README.md, config/tech-docs.yml, requirements.txt, script/test
Add Travis integration to run the linkchecker over the generated docs.
The linkchecker found a couple of broken links, so this fixes them as well.
Code review.
Verify Travis build passes.
Anyone but myself.
=> Run linkchecker over docs in Travis.

source/documentation/deploying_apps/deploying_django.md, source/documentation/deploying_apps/deploying_node_js.md, source/documentation/deploying_apps/deploying_rails.md, source/documentation/deploying_apps/deploying_static_sites.md, source/documentation/deploying_apps/index.md
Rewrite to describe the goal rather than specifying using Git.
Preface specific advice about Git with "if you are using Git".
Clarify that the directory you push from should contain *all* the app
code and config files (assuming it's not worth a digression to explain
how you can configure to look in different folders).
#136104121
When I’m deploying an app to the PaaS for the first time
I need to understand how my files must be checked out of a local folder
So that I can successfully deploy to the PaaS.
Acceptance Criteria
Documentation is clear what is meant by ‘check out’. If there’s a
specific way that users must do this then we should say so.
User Research
During lab testing, a participant used SVN instead of Git to check out
the app. This meant that his manifest file was not in the …
=> Clarify checking out code

source/documentation/deploying_apps/jenkins.md, source/documentation/troubleshooting/lockouts.md, source/index.html.md.erb
Reorganise Jenkins docs, try to remove impression that using custom
script deployment is less secure. Document issue with login rate limit
https://www.pivotaltracker.com/story/show/136104045
"In our current jenkins docs
(https://github.com/alphagov/paas-tech-docs/blob/01a111ddb7ea95951e2f0d2
c809b317acc292fd5/source/documentation/deploying_apps/jenkins.md), we
recommend users log in every time job runs. This is so that they don't
have to handle secure storage of CF secrets (which is a file with a
logged-in token cf CLI produces after logging in). However our platform
has protection to lock accounts that log in 5 times in 5 minutes. If
someone has a lot of jenkins jobs, or small jobs that run often, they
can easily hit this limit and lock themselves out. As it has already
happened once and …
=> Reorganise Jenkins doc, document rate limit

source/documentation/troubleshooting/line-endings.md
Explain to Windows users that pushing with CRLF line breaks can cause
errors.
Story: https://www.pivotaltracker.com/story/show/135421943
Note that Cloud foundry at this time runs all applications in Linux
containers.
Add some instructions to the docs so that new Windows users know that
files with CRLF line endings won't always work
turn off the autocrlf setting in git
Or make sure that you specify the interpeter to be used in a command in
manifest.yml or a Procfile eg. command: ruby foo.rb
We had an issue in user research where a user tried to push our sample
ruby app from a windows machine in a git repo with autocrlf turned on.
It failed because Linux was unable to understand the shebang line.
=> Document CRLF issue

source/index.html.md.erb
Previously we added the actual prose but didn't place it here, so it didn't
appear in the built documentation.
It looks like this in my Firefox, which is less than ideal, but not much different to other terminal output sections we have.
Check the CRLF line endings content appears in built tech docs
Anyone but @bleach
=> [#135421943] Add CRLF line endings to troubleshooting section

source/documentation/deploying_services/postgres.md
#131250593
Acceptance Criteria
Signposting to logging documentation is included at appropriate point within ‘Creating a Postgres service’ section of the docs.
User Research
Users want more control/visibility of Postgres for troubleshooting purposes
=> [#131250593] Add link to logs section

source/documentation/deploying_services/postgres.md, source/documentation/troubleshooting/postgres.md, source/index.html.md.erb
#131250633
Provide more details about checking service is bound.
Advise using "restage" rather than "restart" to make sure it binds.
Original story: 
As a user in order to check that an app and Postgres instance have bound successfully, I want to know how to check the service status.
Acceptance Criteria
When a user follows documentation steps to bind app with a backing service, the following step should tell them how to check service status.
User Research
Users felt they only got a ‘proxy answer when checking if app + Postgres instance bound successfully
=> [#131250633] More detail about checking service is bound

manifest.yml, release/push
Story: [Deployment Pipeline for Tech Docs to cloudapps.digital](https://www.pivotaltracker.com/story/show/136353551)
paas-tech-docs is the official name in production. Also it is the one set in manifest.yml.
Code review
Not me
=> [#136353551] Change tech-docs name to paas-tech-docs

source/documentation/getting_started/quick_setup_guide.md
Replace an errant non breaking space – which causes the heading to be indented – with a normal space.
=> Fix errant non breaking space

README.md
Replace all the content about old URLs with the new URL.
The new `docs.cloud` URL was made available in Pivotal story #136353673. The
old `government-paas-developer-docs.readthedocs` URL was redirect to
`docs.cloud` in Pivotal story #136429263.
There is still an outstanding Pivotal story #139284061 to redirect
`paas-tech-docs.cloudapps` to `docs.cloud`, but I think it's sufficient to
remove the notice from the README for now.
Check that the new content and my rationale for changing it makes sense.
Probably @benh-gds.
=> [#136353673 #136429263] Remove old URLs from README

source/documentation/deploying_services/postgres.md, source/documentation/troubleshooting/ssh.md, source/index.html.md.erb
[#39826733 Document "restore from latest snapshot feature"](https://www.pivotaltracker.com/story/show/139826733)
What?
----
In the story [#139361587](https://www.pivotaltracker.com/n/projects/1275640/stories/139361587) we added the feature to restore postgresql DBs from the latest snapshot of a existing postgresql service.
We need to add this to the tenant manual.
It works as described in this PR: https://github.com/alphagov/paas-cf/pull/784
How to review?
--------------
Read it ;)
Who?
---
Anyone but @keymon
=> [#139826733] Document restore from latest snapshot feature

source/documentation/troubleshooting/ssh.md
The extra newline was causing the nested unordered list to be rendered as a
codeblock with literal `+` characters before each line and the next ordered
list item to be rendered as `1.` instead of `2.`.
I'm not happy with the subtly of this change, but no amount of indentation
changes to the unordered list made it render correctly.
Before:
After:
Code review would be sufficient. But if you'd like to test it yourself:
1. Checkout the branch.
1. Run the test server with `bundle exec middleman server`
1. Check the rendering at http://localhost:4567/#creating-tcp-tunnels-with-ssh
Anyone. It doesn't change the copy or meaning, so I don't think it needs someone from content.
=> [#139826733] Fix list formatting in SSH tunnel docs

source/documentation/deploying_services/postgres.md, source/documentation/troubleshooting/ssh.md
We don't want users to waste time hitting the problems we're currently debugging with SSH tunnels, so I've explained the limitation.
Because we expect people using "restore from snapshot" to use SSH tunnels, and also because we want to get feedback from them, we mark that feature as experimental.
Read the docs and form an opinion about if this is clear and accurate for our users.
Anyone but @bleach.
=> [#139826733] Restore snapshot experimental, ssh has issues

source/documentation/deploying_apps/deploying_docker_image.md
Said local images are not *currently* supported.
Highlighted not using in production.
Said we wanted feedback from service teams, and to say they should contact us if they want to use in production.
Read the words and check they are not false.
Anyone except @tomskerous.
=> Make docker language more 'open'

source/documentation/getting_started/limitations.md
Remove docker and route services from limitations section as both features are currently enabled.
Sanity check
Not @combor
=> Remove docker and route services from limitations section

source/documentation/deploying_services/postgres.md, source/documentation/troubleshooting/ssh.md
Story: [Resolve issues with large database imports](https://www.pivotaltracker.com/story/show/141785699)
We have fixed the server side issue with SSH. There is still an issue with cf cli, but the tenants can use the standard ssh client as a workaround.
* Does is make sense?
* Did I write decent british english?
Not me
=> [#141785699] Update workaround SSH instructions

source/documentation/getting_started/quick_setup_guide.md
We are replacing passwords with invites in alphagov/paas-cf#868 so we no
longer need to tell people to reset their password after the first login.
Check that the new content makes sense. It makes sense to review this at the same time as alphagov/paas-cf#868.
@jollery or @tomskerous may want to review the content.
=> [#134175741] Remove password references from getting started

source/documentation/using_ci/travis.md
What
====
Change to show only config required to deploy
It confused me that we referenced a complete .travis.yml file, but were
telling the users to add to a .travis.yml file. This changes to list
just the config required to add to .travis.yml file in order to deploy
Who can review
==============
anyone but me
=> Change to show only config required to deploy

source/documentation/troubleshooting/ssh.md
The bug that this relates to has been fixed upstream with version 6.26
of the CLI. This therefore updates our warning to reflect this.
I've left the warning in place but made it specific to 6.24 and 6.25 of the CLI because there are likely to be many tenants who still have these versions installed.
Read, check it makes sense.
Not me.
=> [#142400337] Update SSH warning now that the 2GB bug has been fixed

source/documentation/deploying_services/use_a_custom_domain.md, source/index.html.md.erb
Add documentation on the new CDN broker service.
Check links, readability, and accuracy. It is recommended to use this documentation to test the CDN broker in the corresponding pull request on paas-cf (which has not been raised yet, so this is still technically WIP).
The broker needs to be deployed to production. 
Anyone but @combor, @paroxp, @saliceti or me
=> [#141231851] Add documentation for CDN broker

source/documentation/deploying_apps/names_routes_domains.md, source/documentation/getting_started/limitations.md
This commit is to remove the 'getting started' section of the tech docs that say we don't support custom domains - because now, we do.
I've also updated the section: 'we recommend using a CDN to configure your custom domain' to now link to the 'Using a custom domain' section in the docs.
Read the content and check it makes sense.
Anyone but me.
=> [#146441331]Update custom domains info

source/documentation/deploying_apps/names_routes_domains.md
So that it doesn't go to the live site when you're running the documentation
service locally for development and so that linkchecker can validate whether
the anchor exists[0].
[0]: Although linkchecker isn't currently doing this for some reason.
1. Checkout the branch: `git fetch && git checkout bugfix/146441331-make_link_relative`
1. Run the server locally: `bundle install && bundle exec middleman server`
1. Visit the changed content at http://localhost:4567/#custom-domains
1. Click the link and confirm it takes you to content at http://localhost:4567/#using-a-custom-domain
Anyone
=> [#146441331] Make custom domains anchor link relative

source/documentation/deploying_apps/stopping_and_deleting_apps.md, source/documentation/getting_started/quick_setup_guide.md, source/index.html.md.erb
Add info on stopping apps, deleting apps and services in the right
order, and also how to delete routes if you forget the -r flag.
Add a line at the end of the “deploy a simple app” in quick setup guide
to remind users they can clean up after themselves.
Content has been reviewed by @bleach while in GDoc form, although there
have been some amendments for clarity once I’ve seen it in context and
formatted.
=> Add docs on app/service deletion

source/documentation/using_ci/travis.md
Updated the internal anchor link for the 'Names, routes and domains' section so that it links to a valid hash.
Verify that [this is the right place to link to](https://docs.cloud.service.gov.uk/#names-routes-and-domains).
Anyone
=> Fix incorrect anchor link

source/documentation/deploying_services/index.md, source/documentation/deploying_services/mysql.md, source/documentation/deploying_services/postgres.md, source/documentation/getting_started/before_you_start.md, source/index.html.md.erb
As we're slowly implementing the MySQL support on our platform, we'd
like to have the documentation for our tenants to refer to, when they're
dealing with the service.
I have mainly copied the entire postgres section and applied minor changes to naming and tools.
Please, see my comments in pivotal story about this PR before merging.
- Read through the changes
=> [#141705365] Document the use of MySQL

source/documentation/deploying_services/mysql.md
We have found that Rails, Django and PHP all don't use TLS by default. It's
not possible to provide a database URI/URL with query parameters that
satisfies most of them. We're going to defer writing more specific
documentation for each individual language until we understand what people
need a bit better. This might result in more support requests in the
meantime.
Check if the words make sense.
This can be merged prior to us forcing TLS support.
Anyone.
=> [#147829023] MySQL: Some libraries don't use TLS by default

source/documentation/deploying_apps/deploying_node_js.md
We had a support request from someone that followed this example, had to
update the versions to correspond with what PaaS currently provides, and
used:
"engines": {
"node": ">= 6.0.0",
"npm": ">= 3.0.0"
}
The nodejs-buildpack resolved this to NodeJS 7.8.0 (the latest we had at the
time) and downgraded NPM from 4.2.0 to 3.0.0 (for reasons I don't understand).
These two versions were incompatible so it failed with:
Downloading and installing npm >= 3.0.0 (replacing version 4.2.0)...
npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/tmp/app/.cloudfoundry/node/bin/node" "/tmp/app/.cloudfoundry/node/bin/npm" "install" "--unsafe-perm" "--quiet" "-g" "npm@>=" "3.0.0"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may …
=> [SUPPORT] Change versions in NodeJS example

source/documentation/using_ci/index.md
It's not currently made obvious that we have a policy that usernames should be
email addresses. One result of this is that users request CI accounts without
including email addresses, the support person has to ask them for an email
address and there's a delay in getting what they need.
This commit makes it clearer that an email address is required when requesting
CI users.
- `bundle exec middleman server && open 'http://127.0.0.1:4567/#credentials-for-automated-accounts'`
- proof read text
Anyone but @bleach. Comments welcome from @philandstuff
=> Explain that CI accounts need email addresses

source/documentation/getting_started/system.md, source/index.html.md.erb
This commit adds the copy regarding the statuspage as provided by the
product team.
1. Run `bundle install`
1. Run `bundle exec middleman server`
1. Check newly added section
Not me
=> [147125641] Adding statuspage information to tech docs

source/documentation/deploying_apps/deploying_docker_image.md, source/documentation/getting_started/limitations.md, source/documentation/overview/benefits.md
This is a minimal change that means that our docs remain correct.
@jonathanglassman and myself are going to follow this up with more detail around what "support" means and helping users to choose between standard buildpacks, custom buildpacks and Docker images.
Preview the docs and verify they will be correct when https://github.com/alphagov/paas-cf/pull/989 is merged.
Not @bleach or @jonathanglassman
=> [#146445463] Explain that custom buildpacks are now available

source/documentation/deploying_apps/buildpacks.md, source/documentation/guidance/buildpacks, source/index.html.md.erb
Added content around standard and custom buildpacks
- New section under Deploying Apps which defines buildpacks and specifies how to use custom buildpacks
- New section, Guidance, at the bottom of the document, which provides around when you should and should not use custom buildpacks, and some advantages of them compared to docker images
This is the first draft and can be iterated; I'll speak to people next week about expanding the content around the responsibilities of supporting a custom buildpack or Docker image, and what responsibilities apply to running an app in production long term.
Please review and see if material and guidance are correct or need any amends or additional content.
Anyone apart from me can review this.
=> Document buildpacks

source/documentation/deploying_services/database_services.md
Have added small sections on each backing service with associated h2 headings. This is to call out the current backing services in the left-hand navigation so that users can scan and quickly see these sections. I have not added them as h3 headings as this would mean editing the config yaml file so that all h3 headings are in the left-hand nav which would not be a good experience for the user. Related to https://www.pivotaltracker.com/story/show/149301683 
Check to see if any different or additional content is required in these sections i.e. any specific information that we want to call out on the different backing services.
Anyone but me.
=> Add sections for PostgreSQL, MySQL and MongoDB

source/documentation/deploying_services/database_services.md, source/documentation/deploying_services/index.md
- Re-organise the "Deploy a Backing or Routing Service" section to remove duplicated content.
- Remove duplicated headings within the "Deploy a Backing or Routing Service" section. These duplicated headings were mistakenly implemented when completing previous PR
Check that re-organisation has not removed any content inadvertently or caused a change in meaning.
Anyone in PaaS team; have requested Dan and Tom.
=> [#149301683] Deploying services section re-org

source/documentation/deploying_services/use_a_custom_domain.md
Re-drafted and re-organised custom domain documentation, as per https://www.pivotaltracker.com/story/show/150299463, specifically:
- Setting up a custom domain section is now focused on minimal steps to get this task accomplished, and incorporates feedback from deskpro tickets to make it less confusing
- Configuration options, troubleshooting and custom domains supplementary information consolidated into three separate sections after the setup section
- General re-drafting of content to more high-level and applicable to variety of users
Check that the setup of custom domain documentation makes sense.
Anyone apart from Jon Glassman or Chris Farmiloe
=> Custom Domain documentation

source/documentation/deploying_services/use_a_custom_domain.md
A code block was not getting rendered correctly due to incorretcly being
indented.
Code review should be enough
not @chrisfarms
=> Fix code block formatting in custom domain docs

source/documentation/troubleshooting/ssh.md
The buildpack launcher process that starts the application sets this
environment variable[1] before sourcinf the profile files as part of
launching the app. The diego ssh handler doesn't set this. This means
that for buildpacks that don't override this in their own .profile files
the environment won't work. The Python buildpack is an example, and
means that it's somewhat tricky to run tasks against the app (eg
Django's manage.py).
[1]https://github.com/cloudfoundry/buildpackapplifecycle/blob/master/launcher/main.go#L37-L40
This arose from a support ticket - 8202.
Verify that the change makes sense.
Not me.
=> [Support] Add setting of DEPS_DIR to ssh profile instructions.

source/documentation/deploying_services/database_services.md
This adds a brief note about changing service plans and how long they
might be expected to wait for the changes to take effect. We also
document the apply_at_maintenance_window param which is available for
RDS-broker instances.
⚠️  https://github.com/alphagov/paas-cf/pull/1049 should be merged before this.
Proof read, check formatting.
=> [#150879493] Add info about changing plans with update-service

source/documentation/troubleshooting/index.md
`_grokparsefailure` is a generic tag that any grok filter will throw
by default.  By setting a tag specific to the particular filter, it
makes it much clearer exactly where in the filter processing the parse
failure happened.
This filter configuration already did this for the router grok
parsing (with `_routerparsefailure`); this commit does the same for
the syslog grok parsing.
=> logit logstash config: clearer parse failure tag

source/documentation/deploying_apps/deploying_django.md, source/documentation/deploying_apps/deploying_node_js.md, source/documentation/deploying_apps/deploying_rails.md, source/documentation/getting_started/before_you_start.md, source/documentation/overview/benefits.md, source/documentation/troubleshooting/postgres.md
Updated tech docs to reflect that multiple backing services are supported by PaaS rather than just PostgreSQL.
1. Check that content makes sense and is consistent with https://docs.google.com/document/d/1Ilpx4Ekibo0o3mT0xqWyFus2tqxrBE7scmj_bxC2yBI/edit#
=> [#152315819] Backing service update

source/documentation/deploying_apps/buildpacks.md
Update documentation to reflect that `cf buildpacks` can be used to check installed buildpacks and version numbers.
=> update to reflect cf buildpacks command

source/documentation/deploying_apps/deploying_docker_image.md
Making it explicit that we support 3 Docker staging approaches, but
local images isn’t one of them.
=> Local docker images aren't supported

source/documentation/troubleshooting/ssh.md
Updated one of the commands a user needs to run to setup their environment when ssh-ing onto an instance to be more defensive.
The reason for the change is that bash complains that the file doesn't exist, which, although not a big issue, it could easily be avoided.
1. Copy and paste the new command after you ssh'd onto an instance to ensure that existing functionality didn't break.
Anyone.
=> Check ~/.profile exists before sourcing it

source/documentation/troubleshooting/index.md
Update Logstash filter to create fields for app/space/org
We found syslog_host contained these fields but it caused some confusion as it
isn't the most obvious place to find the app name.
Creating separate fields for these will hopefully be more intuitive and make it
easier to produce queries when dealing with multiple apps shipping logs to a
single ELK stack.
1. Apply this configuration to an ELK stack
2. Ship logs to that ELK stack from CloudFoundry
3. Look in Kibana for the app / space / org fields
Anyone familiar with logstash configuration.
=> Update Logstash filter to create fields for app/space/org

source/documentation/troubleshooting/index.md
We didn’t have anywhere in the nav or h2s that talked about logging
services. Bumped the H3 to a H2 and added the word “Using” to help it
make more sense in the context.
=> Bumped the logging services up the hierarchy

source/documentation/monitoring_apps/metrics.md
The paragraphs in step 3 were not indented, so it was not clear to
see they were only relevant to step 3. The knock-on effect of this
was step 4 actually rendered as step 1, which was incorrect.
Not me
=> [#152653609] Fix indentation for metrics exporter ordered list

source/documentation/monitoring_apps/metrics.md
We will rename the paas-cf-apps-statsd repository to paas-metric-exporter and the Tech docs should reflect this change.
We decided to rename the repo to metric-exporter instead of metrics-exporter as the application name is already metric-exporter and we wanted to keep it consistent.
Sanity check.
Not @46bit or @bandesz
=> [#153084314] Update the metrics exporter repository urls

source/documentation/deploying_services/database_services.md
Removed Redis High Availability content (https://docs.cloud.service.gov.uk/#high-availability-plans-redis) as we are not using Compose with Redis, as per story https://www.pivotaltracker.com/story/show/153435654
1. Check if any other redis content needs to change
=> Remove Redis High Availability content

source/documentation/troubleshooting/tracing.md, source/index.html.md.erb
Zipkin was enabled in the Cloud Foundry router which allows developers to trace HTTP requests and responses. We want our tenants to know about this feature.
Read the Troubleshooting/Tracing requests paragraph and check if it makes sense.
Not @bandesz
=> [#148415719] Add docs about tracing requests to troubleshooting (Zipkin)

source/documentation/deploying_services/database_services.md
Fix unordered list in snapshot instructions. This was at the wrong indentation level which caused it to be rendered as a single sentence. Pulling it back 2 spaces fixes it.
Henry and I used these instructions while working on a story but overlooked this part because I was too lazy to read the long sentence. I realised after that the plan needs to match.
1. Merge.
Anyone.
=> Fix unordered list in snapshot instructions

config/tech-docs.yml, source/documentation/deploying_services/use_a_custom_domain.md
Links to the product pages shouldn't have a file extension because
Middleman renders them without and that's how they are referenced in the
product pages themselves.
Most of these are in the header, but there were also some references to the
support page within the custom domain documentation.
These also caused the requests to redirect off of `service.gov.uk` and go to
`cloudapps.digital` because of a bug that we're fixing in a separate story.
1. Follow all of the links in the top-right header and check that they work.
1. Follow all of the support links in …
=> [#152632922] Remove file extensions from product page links

.template_version, source/stylesheets/modules/_app-pane.scss
Using the following command and accepting all changes except `.gitignore`
which would have partially reverted 2f9a75c:
bundle exec middleman init . -T alphagov/tech-docs-template
The update address two issues that have been fixed upstream:
- alphagov/tech-docs-template#118 to re-add H1 dividers which we already
applied in a5ab659
- alphagov/tech-docs-template#120 to render correctly when Javascript is
disabled
1. Check that there are thick horizontal lines before each H1 as shown in the screenshots of alphagov/tech-docs-template#118
1. Check that the page renders when Javascript is disabled ([see how to …
=> [#153177409] Update tech-docs-template

.gitignore, Gemfile, Gemfile.lock, release/generate-manifest, release/push, release/test, spec/release_spec.rb
This adds a new hostname to the deployed app, which in production will be `docs.cloud.service.gov.uk` and in development would be `docs.${DEPLOY_ENV}.dev.cloudpipeline.digital`. This keeps it in line with the product page and is a step towards removing the `paas-tech-docs.cloudapps.digital` host.
Code review
Not @46bit @camelpunch
=> [#153091168] Deploy with docs.cloud.service.gov.uk hostname

source/documentation/deploying_apps/production_checklist.md, source/documentation/managing_apps/quotas.md, source/documentation/managing_apps/scaling.md
Changed "at least two app instances" to "more than one app instance" so that tenants do not think they just have to run two instances. Also added detail on why they should do this.
1. Check the content addresses the story https://www.pivotaltracker.com/story/show/153744593
Anyone except Jon Glassman. Dan Carley preferred as he wrote the original story.
=> [#153744593] More than one instance

source/documentation/monitoring_apps/metrics.md
Due to changes to the paas-metrics-exporter there are additional 
metrics that were not captured in our documentation. This was reported by a tenant. 
1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected. No links have been changed.
Not @LeePorte
=> [SUPPORT] Added additional metrics

source/documentation/troubleshooting/ssh.md
With the latest CF upgrade, some of the environment files created by the buildpacks have moved (upstream story - https://www.pivotaltracker.com/n/projects/1042066/stories/151381713).
This PR fixes the instructions to reflect these changes, I've done this as 2 commits:
* The first adds the new directory to the list of ones to check.
* The second changes this entirely to use the launcher command to start a new bash shell with the correct environment setup.
I think it's preferable to use the launcher command as it avoids the need to track changes in upstream.
1. Manually check that any removed or renamed …
=> [Support] Fix the ssh environment instructions

source/documentation/troubleshooting/password.md, source/index.html.md.erb
We have enabled the self service password reset feature and want to
bring it to the attention of tenants who may be looking for what to do if they have fotgotten their password.
* Check it makes sense
* Preview it `bundle exec middleman server` 
not @chrisfarms or @henrytk
=> [#143584125] Add link to self-service password reset

source/documentation/deploying_apps/deploying_django.md, source/documentation/deploying_apps/deploying_docker_image.md, source/documentation/deploying_apps/deploying_rails.md, source/documentation/deploying_services/database_services.md, source/documentation/getting_started/before_you_start.md, source/documentation/guidance/buildpacks.md, source/documentation/guidance/php-database.md, source/documentation/troubleshooting/password.md, source/documentation/using_ci/travis.md
Correct typos in tech docs:
- Spelling mistakes
- Missing bullet formatting
- Cloudfoundry => Cloud Foundry
1. Check changes are correct
Anyone except Jon Glassman.
=> Correct typos

source/documentation/deploying_services/index.md
We are making each of the backing service sections more "self-contained" so that users get a single walkthrough for each backing service.
This change mirrors the previous work done for the PostgreSQL section but for our MySQL section.
Not @chrisfarms or @jonathanglassman
=> [#154638133] "self-contained" mysql section

source/documentation/deploying_services/index.md
Added links from Bind a MySQL app to the Guidance section on how to securely connect either a Drupal app or a Wordpress app to MySQL using SSL.
@LeePorte
=> Added MySQL links to Guidance section

source/documentation/deploying_apps/buildpacks.md, source/documentation/deploying_apps/deploying_docker_image.md, source/documentation/guidance/buildpacks.md
https://www.pivotaltracker.com/story/show/154331970
What?
----
We want to document the responsibility model for the users using Docker
on CF vs. using buildpacks. We can write a document inspired on
https://aws.amazon.com/compliance/shared-responsibility-model/,
including a table or image that would list the different layers
of the application, runtime and platform.
We also add links when explaining buildpacks and docker images.
How to review?
--------------
- Proof reading.
- Preview it by running the server locally. See Readme for details.
Who?
----
Anyone but @keymon or @jonathanglassman
=> [#154331970] Add shared responsibility model section

source/documentation/deploying_services/index.md
Describe how a [PaaS Elasticache Broker](https://github.com/alphagov/paas-elasticache-broker) user can connect to their service instance from their local machine using [Conduit](https://github.com/alphagov/paas-cf-conduit). 
1. Check the content addresses the story
Anyone except @jonathanglassman and @camelpunch.
=> [#155439160] Connect to Redis through Conduit

source/documentation/deploying_services/database_services.md, source/documentation/deploying_services/index.md
Updates to backing services clean up story as part of the approval process. Added content stating the following:
- MongoDB and ElasticSearch are trial services available on private beta
- Contact the PaaS team to request information and instructions on how to access and use this service for your app
- Moved TLS connection text to MongoDB and ElasticSearch sections
- Updated information architecture on user-provided services
1. Check that it fulfils requirements …
=> Clean up backing services part 2

LICENCE, README.md
Added MIT licence and a reference to the MIT licence in the readme.md file. This is in line with https://docs.google.com/document/d/1ol86Zvp7DuJ9CYumGC9UisAUUhp4kzwMDEjYKEu_ADo/edit#heading=h.pcmybcsnrr87
=> Add MIT licence to tech docs and tech docs readme

source/documentation/getting_started/limitations.md
Remove "API access may have brief outages during beta" section. PaaS team did the work required to monitor and remove downtime during deployments.
1. Check that it addresses https://www.pivotaltracker.com/story/show/155903882
=> Remove API outages section

source/documentation/deploying_apps/stopping_and_deleting_apps.md
Corrected the Deleting services section of the tech docs to specify:
- you do not need to delete an app's services before you can delete that app
- you should unbind a service instance from the app it is bound to before you delete that service instance
1. Check that the content meets the requirements of story: https://www.pivotaltracker.com/story/show/155065780
=> Correct deleting services section

.github/PULL_REQUEST_TEMPLATE.md, source/documentation/deploying_services/index.md
What
----
Redis is not private beta anymore and it is enabled for everyone
after[1]. It is not required to contact support to get it enabled.
We also fix some spurious trailing whitespaces (my editor did ;))
And we update the github pr template
[1] https://github.com/alphagov/paas-cf/pull/1327
How to review
-------------
Coode review.
Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected.
Who can review
--------------
Anyone but @keymon. Maybe @alext
=> [#154770854] Do not require request to get access to redis

source/documentation/deploying_services/index.md
Update documentation about how to use the updated Conduit plugin with Redis service instances and redis-cli.
❗️ Do not merge until the new version of conduit is published to the Cloud Foundry Plugin repository.
Not me.
=> [#155431687] Update Redis Conduit docs

source/documentation/deploying_apps/index.md, source/documentation/deploying_services/index.md, source/documentation/overview/benefits.md
What
----
Added data security classification section to the Deploying apps and backing services sections of the tech docs, stating that the PaaS can store data up to "official".
How to review
-------------
1. Check that it covers https://www.pivotaltracker.com/story/show/156810789
Who can review
--------------
Anyone except Lee Porte and Jon Glassman
=> Data official

source/documentation/deploying_services/index.md, source/documentation/overview/benefits.md
What
----
- Added new data security classification section to the backing service content
- Replaced backing service data security content with links to new section
- Added link to data security classification section into the Benefits section
How to review
-------------
1. Check it fulfils last comment on https://www.pivotaltracker.com/story/show/156810789
Who can review
--------------
=> Update data security

source/documentation/deploying_services/use_a_custom_domain.md
What
----
Remove "optionally" from "optionally cache" to clarify that caching happens by default.
This will address user feedback that this phrase is potentially misleading.
How to review
-------------
1. Check it fulfils https://www.pivotaltracker.com/story/show/157509104
Who can review
--------------
Anyone excluding Jon Glassman and Andras Ferencz-Szabo
=> Clarify caching

source/documentation/deploying_services/index.md
What
----
Updated backing service plan names in line with new naming convention, and to reflect encryption offered as standard.
How to review
-------------
1. Check if accurately reflects the story: https://www.pivotaltracker.com/story/show/157470481 and also the latest announcement.
Who can review
--------------
=> Updated backing service plan names

source/documentation/index.md, source/documentation/orgs_spaces_users/index.md
The links to paas-admin were linking to the uaa login page rather than to the paas-admin url: admin.cloud.service.gov.uk
Check the links I changed are ok
Not me
=> Use "admin" url not "login" when linking to pazmin

source/documentation/index.md, source/index.html.md.erb
What
----
- Removed privacy policy from the PaaS tech docs as the overall privacy policy is a cross-GDS internal facing document, and this does not need to be included in the tech docs as well. 
- Removed link to privacy policy with link to privacy notice.
How to review
-------------
Who can review
--------------
Lee Porte
=> Remove privacy policy

source/documentation/using_ci/index.md, source/documentation/using_ci/travis.md
What
----
Updated CI section:
- Removed duplicated information
- Brought in line with GDS style
- Added in warning to focus on encryption of sensitive information when choosing a CI tool
Updated Travis section:
- Write active numbered instructions
- Include warning about information encryption
How to review
-------------
1. Check it covers requirements of https://www.pivotaltracker.com/story/show/158791278
Who can review
--------------
Anyone except Jon …
=> Travis ci update

source/documentation/using_ci/jenkins.md
What
----
Broken link reported in slack here:
https://gds.slack.com/archives/CADHV9267/p1534328991000100
> The link on
> > Find out more about setting credentials for automated accounts in PaaS.
> seems to be broken - is the advice at the moment to just set up another
> user account? there's no special way to set up a CI account at the
> moment?
Looks like this was broken when we renamed the header in 1802ad1e2.
How to review
-------------
Run locally and check the link isn't broken anymore.
Who can review
--------------
Anyone
=> Fix broken link to configure your ci tool accounts

source/documentation/deploying_services/configure_cdn.md, source/documentation/deploying_services/use_a_custom_domain.md
What
----
Specified that users cannot use the `cdn-route` service with an apex domain, but must instead use a custom domain. Have also tidied up the text to use "app" rather than "application".
How to review
-------------
1. Check that changes fulfil https://www.pivotaltracker.com/story/show/159731433
Who can review
--------------
Anyone except Jon Glassman or Jonathan Matthews
=> Custom subdomain prefix

source/documentation/deploying_services/index.md
What
----
Added in content to state that you can only upgrade your PostgreSQL and MySQl plans using the `cf update-services` command if the new plan has the same encryption type as the current plan. If the encryption types are different then you have to create a new service and migrate the data over.
How to review
-------------
1. Check that it fulfils https://www.pivotaltracker.com/story/show/159563732
Who can review
-------------- …
=> Upgrading plans with same encryption type

source/documentation/deploying_apps/buildpacks.md, source/documentation/deploying_apps/deploying_django.md, source/documentation/deploying_apps/deploying_java.md, source/documentation/deploying_apps/deploying_node_js.md, source/documentation/deploying_apps/deploying_rails.md
What
----
- Removed references to outdated software in Python buildpack
- Tweaked Python content to be more active
- Created new section on software versions in buildpacks
- Created new section for each app referring to other new section, with links to cloud foundry docs as required
How to review
-------------
1. Check it fulfils story: https://www.pivotaltracker.com/story/show/160099400
Who can review
--------------
Anyone except Jon Glassman or Sam Crang
=> Outdated software buildpacks

source/documentation/deploying_apps/env_variables.md, source/documentation/deploying_apps/index.md, source/documentation/deploying_services/index.md
What
----
- Added manifest method of binding an app to a backing service.
- Made text more active and in line with style.
- Added new "Connect to a [NAME] service from your app" section. This contains the existing content on TLS connections and environment variables. It links to the environment variables section in deploying apps, which now has the VCAP_SERVICES example text.
How to review
-------------
1. Check it fulfils story: …
=> Add manifest method to backing service tech docs

Gemfile, Gemfile.lock
This avoids the following warning when bundling:
>  The git source `git://github.com/alphagov/middleman-search.git` uses
>  the `git` protocol, which transmits data without encryption. Disable
>  this warning with `bundle config git.allow_insecure true`, or switch
>  to the `https` protocol to keep your data secure.
This also allows bundling to work when operating behing a broken ISP
filtering proxy server that blocks non-http access (eg VirginMedia)
How to review
-------------
* Verify `bundle install` still works.
* Verify that this doesn't actually change any versions.
Who can review
--------------
Not me.
=> Use https:// instead of git:// for middleman-search gem.

source/documentation/deploying_services/configure_cdn.md, source/documentation/deploying_services/route_services.md
What
----
Fixed broken links:
1. Change link on user-provided service instance from `https://docs.cloud.service.gov.uk/https://docs.cloudfoundry.org/devguide/services/user-provided.html` to	`https://docs.cloudfoundry.org/devguide/services/user-provided.html` by removing superfluous "\"
2. Changed cdn-route link to `deploying_services/use_a_custom_domain/#set-up-a-custom-domain-using-the-cdn-route-service`
How to review
-------------
1. Check that links now work …
=> Fix broken links

Gemfile.lock, source/documentation/troubleshooting/ssh.md
What
----
Updated to latest version of tech doc tool gem (1.6.1). This includes improvements to the search functionality, the left-hand nav, and a working API reference function.
How to review
-------------
1. Check that the docs still work as expected and the update hasn't broken them.
Who can review
--------------
=> Updated tech doc gem

Makefile, source/documentation/deploying_services/postgresql.md
What
-----
When running linkchecker directly against the build directory, it checks
links that move up/across the directory hierarchy only for link correctness, not
target existence. This means that, before this commit, our standard "make test"
pre-merge only checked that internal links reached pages which exist in
around 40% of cases. Using `--check-extern` isn't an option, as this not
only makes linkchecker check off-site hosts, but will also fail with
`/`-prefixed, relative (internal) links when it discovers that, on the
filesystem, `/stylesheets/foo.css` doesn't exist. There doesn't appear
to be a way to tell linkchecker to assume a `file://path/to/build/dir`
base URL.
To get round this, we use the fact that linkchecker *will* check the
internal consistency of links when given an …
=> Expand linkchecker testing to catch more 404s

source/documentation/getting_started/get_started.md, source/documentation/index.md, source/documentation/monitoring_apps/metrics.md, source/documentation/orgs_spaces_users/index.md, source/documentation/using_ci/jenkins.md, source/documentation/using_ci/travis.md
What
----
Updated tech docs to reflect that the PaaS is now hosted in two locations, London and Ireland:
- Added how to log into both London and Ireland
- Added that a user will have two accounts if they belong to orgs in both London and Ireland
- Added how to log into the London and Ireland admin tools separately
How to review
-------------
1. Check that it fulfils https://www.pivotaltracker.com/story/show/159073525
Who can review
--------------
Anyone except …
=> [#159073525] UK based PaaS

Gemfile.lock
To fix CVE-2018-16470 [1]. This isn't a significant thing for us as
this is a static site generator, so rack isn't running in production,
but it's worth updating to avoid the noise etc.
[1]https://groups.google.com/forum/#!msg/rubyonrails-security/U_x-YkfuVTg/xhvYAmp6AAAJ
How to review
-------------
Code review should be enough
Who can review
--------------
Not me.
=> Upgrade rack to 2.0.6

source/documentation/deploying_apps/names_routes_domains.md, source/documentation/deploying_services/configure_cdn.md, source/documentation/deploying_services/use_a_custom_domain.md
What
----
- Added in warning on domains’ TLS certificates failing to renew
- Brought content in line with style
- Improved structure:
- Setting up a cdn-route service with one or more custom domains
- Adding a custom domain to your existing cdn-route service
- Mapping a subdomain route to your app
- Removing a custom domain from your cdn-route service
How to review
-------------
1. Check it covers https://www.pivotaltracker.com/story/show/161837922
Who can …
=> Custom domains content overhaul

source/documentation/deploying_apps/index.md
What
----
After the launch/announcement of private apps, the section on http->https redirection needs scoping to non-private apps.
This is because the redirection is done at the PaaS border, an interface which app-to-private-app traffic doesn't traverse.
How to review
-------------
- PaaS Dev/Ops: read and agree/comment
- Tech writer: agree that this change doesn't require 2i, or push it into that process as appropriate.
Who can review
--------------
Anyone except @jpluscplusm, but it must have @jonathanglassman's approval before merging.
=> Automatic http->https redirection is only for public routes

source/documentation/deploying_apps/deploying_java.md
What
----
The previous text had some information under the heading *Specify a Java Version* about checking the buildpack version which is irrelevant to specifying the Java version!
Judging by my own experience and others on Slack this information was not helpful and is arguably harmful in sending people further away from the expected answer.
I have changed the text to reflect the required steps to set the JRE version.
How to review
-------------
run locally and go to: `/deploying_apps.html#specify-a-java-version`
Who can review
--------------
anyone but me. CC @richardTowers
=> document how to set JRE version using env var

source/documentation/monitoring_apps/metrics.md
What
----
Updated the tech docs to reflect how tenants can scrape PaaS metrics with a self-hosted Prometheus.
https://docs.cloud.service.gov.uk/monitoring_apps.html#metrics
This update states that tenants are required to deploy the `paas-prometheus-exporter` app in their PaaS space, which provides an end point for Prometheus to scrape the metrics for the apps and services running on PaaS.
How to review
-------------
1. Check that it reflects how the app works, …
=> [WIP] PaaS Prometheus Exporter

source/documentation/monitoring_apps/metrics.md
What
----
* Fix: the paas-metric-exporter is not displaying any metrics but pushes them to a StatsD-compatible server
* Change the order that users should start the prometheus-exporter app first and then set it up in Prometheus
* Fix type: supposed -> supported
How to review
-------------
Code review. I don't think a 2i review is needed as there is no new content.
Who can review
--------------
Anyone.
=> [#162793860] Prometheus exporter documentation fixes

source/documentation/deploying_services/mysql.md, source/documentation/deploying_services/postgresql.md
What
----
Add in content for rebooting a PostgreSQL or MySQL service instance. This is a new feature added at the end of last quarter that must be documented.
How to review
-------------
1. Check it fulfils story: https://www.pivotaltracker.com/story/show/163221757
Who can review
--------------
Initial review: Andras. Subsequent full review: Anyone except Andras or Jon G.
=> Add in content for rebooting a PostgreSQL or MySQL service instance

Gemfile, Gemfile.lock
What
----
Update tech docs to use the latest version of tech docs gem (v1.8.0).
How to review
-------------
Who can review
--------------
Anyone excluding Jon Glassman.
=> Update docs to use tec docs gems v1.8.0

Gemfile, Gemfile.lock
What
----
Updating the govuk_tech_docs gem
How to review
-------------
- `docker build -t test .` and run`docker run -p 8080:4567 -v $(pwd)/paas-tech-docs:/tmp -it test /bin/sh`
- `cd /tmp` and run `make test`
- Run `bundle exec middleman server`
- Go to `localhost:8080`, preview the content locally and check that it renders as expected
- Manually check that any removed or renamed anchor tags are not in use ([linkchecker](https://github.com/linkcheck/linkchecker) doesn't do this)
Who can review
--------------
Not @mogds
=> Update govuk_tech_docs gem to 1.8.0

source/documentation/deploying_services/elasticsearch.md
What
----
* Removed reference to Elasticsearch 5.x
* Added documentation for upgrading to a different plan version
How to review
-------------
Who can review
--------------
Not @tnwhitwell or @AP-Hunt
=> [#163592114] Deprecate Elasticsearch 5.x

source/documentation/deploying_services/use_a_custom_domain.md
What
----
Users must set both CNAME and TXT records when:
- setting up a cdn-route service with one or more custom domains
- adding a custom domain to your existing cdn-route service
Referenced in https://govuk.zendesk.com/agent/tickets/3592045.
https://github.com/alphagov/paas-cdn-broker/pull/11/files is correcting the broker, the docs must also be corrected.
How to review
-------------
1. Check it fulfils https://www.pivotaltracker.com/story/show/164397255 …
=> Update DNS information output

.travis.yml, source/documentation/deploying_services/postgresql.md
What
----
- Adds content on enabling and disabling extensions in PostgreSQL service instances.
- Removes unneeded content on extensions whitelist
How to review
-------------
1. Check it fulfils https://www.pivotaltracker.com/story/show/163979461
Who can review
--------------
Anyone except Jon Glassman.
=> Enable extensions in PostgreSQL service instances

source/documentation/deploying_apps/index.erb, source/documentation/deploying_services/use_a_custom_domain.erb
What
----
Previously, to insert a warning into the tech docs, you needed to insert a long html string. This has been incorporated into the latest version of the tech doc gem and can be accessed using `<%= warning_text(WARNING TEXT)  %>:
- Changed warning text to use new warning functionality. 
- Changed files from .md to .erb so the functionality works as it is written in Ruby.
How to review
-------------
1. Check that the warning text renders identically to …
=> New warning text functionality

source/documentation/deploying_services/postgresql.md
What
----
Update enabled RDS docs to match reality
We have more extensions enabled since this:
https://github.com/alphagov/paas-cf/pull/1845
How to review
-------------
Read the commit above and review the table
Who can review
--------------
Not @tlwr
=> Update enabled RDS docs to match reality

source/documentation/deploying_services/elasticsearch.md, source/documentation/deploying_services/mysql.md, source/documentation/deploying_services/postgresql.md, source/documentation/deploying_services/redis.md
What
----
There is a bug [1] in tech-docs-gem that causes identical headings on different
pages to be generated with incorrect identifiers. The behaviour is correct for
headings on the same page, but not for different pages as here. Jon Hallam, Jon
Glassman, and I agreed that a workaround using HTML headings was suitable here.
[1] https://github.com/alphagov/tech-docs-template/issues/180
How to review
-------------
1. Code review
2. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected.
3. Check that all the table of contents headings under "Deploy a backing or routing service" work, and go to the right part of the page
Who can review
-------------- …
=> [#163694261] Workaround tech-docs-gem bug by using HTML headings

source/documentation/guidance/pentest.md
What
----
Penetration testing no longer requires AWS authorisation
However, we still want to hear from tenants when they carry out pen tests. This
commit changes our penetration testing guidance to no longer mentioned the need
for AWS authorisation.
How to review
-------------
1. Review the copy
Who can review
--------------
@tnwhitwell for technical accuracy, @jonathanglassman for the quality of the copy.
=> [#165350427] Penetration testing no longer requires AWS authorisation

source/documentation/guidance/upgrading-from-cflinuxfs2.md, source/guidance.html.md.erb
What
----
This documentation is a quick explanation of what the upgrade is and how tenants can manually perform it. The instructions are deliberately generic because tenants deploy their apps in lots of different ways. The link to contact our support will help people who feel stuck.
This new content will be linked to by our admin panel once https://github.com/alphagov/paas-admin/pull/205 is merged.
How to review
-------------
Content review. This will only be live for a short time so only needs to be 'good enough.'
Who can review
--------------
Not @46bit
=> [#165851677] Document how to upgrade from cflinuxfs2

source/documentation/deploying_services/s3.md
What
----
```
luke.malcher [07:30 Uhr]
>The Amazon S3 backing service is in private beta and may not be suitable for all services. To request access and discuss your services needs, contact the GOV.UK PaaS team at gov-uk-paas-support@digital.cabinet-office.gov.uk.
this is no longer accurate - do we need a story to update it? seems like a v small task
we could probably just replace this with "To provide any feedback on this feature, contact the GOV.UK PaaS team at gov-uk-paas-support@digital.cabinet-office.gov.uk."
Would be good to update it before we start shouting about he feature, so that people feel comfortable using it
```
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
=> Update the s3 docs to be accurate about live

Makefile
What
----
See https://wummel.github.io/linkchecker/man1/linkchecker.1.html
```
--no-warnings
Don't log warnings. Default is to log warnings.
```
These warnings could arguably be useful, but in practice it looks like
they fire in an unreliable way, so we're just ignoring them.
Having flakey tests is hurting us more than this tool is helping us
avoid broken links.
How to review
-------------
* Code review is probably enough
Who can review
--------------
=> [#165850892] Don't output Linkchecker warnings

source/documentation/using_ci/index.md
What
----
A tenant asked us to create them some CI users, because this line of our documentation told them to request their creation. But `paas-admin` now allows tenants to do their own user management. As such, this commit stops telling tenants to specially request CI accounts.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit
=> Update the CI docs now paas-admin manages users

source/documentation/guidance/pentest.md
What
----
There used to be a lot of information here that we needed to send to
AWS, but we don't need to do that anymore, so we can afford to ask for
less.
I don't think we care about the things that I've removed.
How to review
-------------
* Code review is enough
* I think there's no need for two-eye review since I'm only removing content
Who can review
--------------
Not Rich, maybe Jon?
=> Reduce number of things to declare about pen tests

source/documentation/getting_started/get_started.md
What
----
The single sign-on function previously only worked for people in GDS with a GDS email address. It now works for everyone with a Google or Microsoft account. This updated content reflects this.
How to review
-------------
1. Check it completes https://www.pivotaltracker.com/story/show/167345982
Who can review
--------------
=> Single sign-on update

source/documentation/deploying_apps/index.erb, source/documentation/getting_started/get_started.erb, source/documentation/troubleshooting/ssh.erb
What
----
Added in content on the Cloud Foundry v3 API:
- add recreating the network policy for deploying a private app
- add content on deploying a static HTML page using the CF API v3
- rename content on deploying a static HTML page to deploying a static HTML page using the CF API v2
- add warning on cf ssh command for v3 of CF API
How to review
-------------
1. Check that it fulfils https://www.pivotaltracker.com/story/show/165305947
Who can review …
=> Add in Cloud Foundry v3 API

source/documentation/troubleshooting/ssh.erb
What
----
Because this is an `<h2>` it gets rendered as a separate section, but it
should actually appear under the "Connecting with SSH section".
How to review
-------------
* Check it matches the level of the other headings in this doc
Who can review
--------------
=> Make "Creating TCP tunnels" as subsection

source/documentation/deploying_apps/buildpacks.md, source/documentation/getting_started/get_started.erb, source/documentation/guidance/pentest.md, source/documentation/managing_apps/scaling.md, source/documentation/managing_apps/ssh.erb, source/managing_apps.html.md.erb, source/troubleshooting.html.md.erb
What
----
Made the following quick win changes from the PaaS Doc-a-thon session:
- Moved `Connecting with SSH` to under `Managing apps`
- Move `Failed login rate limit` to 'Sign into Cloud Foundry' and brought in line with style
- Removed `Troubleshooting > Port environment variable error` from docs
- Updated responsibility model link (`responsibility_model.html#know-your-responsibilities`) in Buildpacks and Penetration Testing sections
How to review
-------------
1. Manually check that any removed or renamed anchor tags are not in use ([linkchecker](https://github.com/linkcheck/linkchecker) doesn't do …
=> Quick wins from Doc-a-thon

source/documentation/deploying_services/postgresql.md
What
----
Changes one word. PostgreSQL is a service, and the sentence is referring to what service plan it should use.
How to review
-------------
Read and consider.
Who can review
--------------
Not @46bit
=> Correct PostgreSQL apps to PostgreSQL services

source/documentation/deploying_services/use_a_custom_domain.erb
What
----
The broker does not require all the configuration parameters anymore.
The broker needs a new DNS challenge whenever the value for domain has
changed, add a warning about this.
How to review
-------------
1. …
Who can review
--------------
Not @tlwr
=> Do not suggest updating CDN domains unless needed

source/documentation/managing_apps/ssh.erb
What
----
Tenants get confused when they tunnel and are ALSO given a
terminal, they try and use the tunnel terminal instead of opening a new
one (which the documentation says to do).
If we add `-T` then users will get a terminal which hangs, and be forced
to use a new terminal
How to review
-------------
Docs review
Who can review
--------------
Not @tlwr
=> Add -T flag to SSH guidance documentation

source/documentation/deploying_services/s3.md
What
----
Previously although it was described how to create public buckets, it was not described how to publicly access objects in those buckets.
How to review
-------------
1. Check the content makes sense
Who can review
--------------
Anyone but me
=> Add documentation for accessing public S3 buckets

source/documentation/deploying_apps/index.erb
What
----
Previously, we pointed readers to the route services documentation to find out 
how to implement an IP whitelist in front of their apps. However, we don't
actually document that or support it as part of the platform. We actually
document how to implement basic auth.
Also adds a pointer to the `re-paas-ip-safelist-service`[1] app for 
implementing an IP whitelist.
[1] https://github.com/alphagov/re-paas-ip-safelist-service
How to review
------------- …
=> Correct reference to route service in private apps

source/documentation/deploying_services/use_a_custom_domain.erb
What
----
- This was getting interpreted as 2 separate commands when copying and
pasting
- Other commands lower down use backslash so stay consistent
Who can review
--------------
Not me
=> Fix newline in cdn-route

source/documentation/deploying_services/elasticsearch.md
What
----
- Remove private beta from elasticsearch page
- Remove note about compatibility because we only have 6.x plans now
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
=> Elasticsearch docs - remove unnecessary/confusing wording

source/documentation/deploying_services/route_services.md
What
----
I've updated where we are point to for the basic auth route service, as Alex has left the team we can't be certain that the original repo would remain.
How to review
-------------
1. Check that it links to the right repo
Who can review
--------------
anyone
=> Update basic auth route service to an alphagov fork

source/documentation/troubleshooting/password.md
What
----
There was only a link to the password reset for Ireland, this adds the link for London and clarifies which link leads to the relevant admin interface.
How to review
-------------
1. Code review
Who can review
--------------
Anyone
=> Add password reset for London

Gemfile.lock, config.rb, config/tech-docs.yml
What
----
1) Updated the tech docs template version to 2.0.5.
2) Activated the tech docs template feature that adds 'contribution' links on each page for users to:
- see the page in the PaaS GitHub repo
- report a problem with the page
There's an example of what this looks like at the bottom of the [Verify tech docs front page](https://www.docs.verify.service.gov.uk/#gov-uk-verify-technical-documentation).
To do this I've:
- added the relevant flag in the tech docs config file
- added code to config.rb to rewrite the 'report a problem' link so it's a mailto rather than a link to create a PR (similarly to Verify tech docs). This is to help users who want to report feedback without using GitHub.
How to review
-------------
1. Preview the …
=> Update tech docs template version and add contribution links

Makefile
What
----
The build is currently failing because it needs to run `bundle install`,
which `make test` currently doesn't run.
Making `build` depend on `dependencies` seems to be the most sensible
way of fixing this.
How to review
-------------
Code review is enough
Who can review
--------------
=> Always fetch dependencies before building

Makefile
What
----
This reverts commit c22c0da8d753031ec9e3bee4a8ecd912bdc13db8.
It turns out the docker image we build that contains the dependencies doesn't have pip installed :rage:.
It's going to turn into a yak shave to get the build working properly,
so let's not even bother.
How to review
-------------
* Code review
Who can review
--------------
=> Revert "Always fetch dependencies before building"

source/documentation/deploying_services/route_services.md
What
----
We are no longer using the ELB and HAProxy which means we do not need to
confuse our users with two X-Forwarded-For headers.
The header will be set in the format defined by our acceptance tests:
```X-Forwarded-For: SOURCE_IPS_COMMA_SEPARATED, INTERNAL_ROUTER_IP```
How to review
-------------
1. …
Who can review
--------------
@jonathanglassman
=> Remove loopback IP from XFF header

source/documentation/deploying_services/postgresql.md
What
----
This PR updates our Postgres documentation with the extensions available for Postgres 11.
When adding Postgres 11 we configured the default and optional extensions, based on RDS's own list.
This commit was done by diffing the extensions listed in the table of optional extensions against the extensions made available in [1]. The results:
```
< chkpass
> citext
> pg_transport
> pgtap
> postgis
< tsearch2
> uuid-ossp
```
The following extensions are in the separate default extensions table so can be ignored:
- `citext`
- `postgis`
- `uuid-ossp`
These extensions have been removed:
- `chkpass`
- `tsearch2`
These extensions have been added:
- `pg_transport`
- `pgtap`
Tables updated to match.
[1] https://github.com/alphagov/paas-cf/pull/2097/files?file-filters%5B%5D=.erb&file-filters%5B …
=> [#169402849] Document the extensions we offer for Postgres 11

source/documentation/deploying_services/mysql.md, source/documentation/deploying_services/postgresql.md, source/documentation/deploying_services/redis.md
What
----
There was nowhere to link to for how to update a redis service to a
bigger plan, so adding one here.
While doing so I noticed that:
* We're suspiciously vague about whether we'll bill you for paid
services
* We have more than two plans for redis now
* Some of the old redis documentation was confusing, and inconsistent
with the docs for postgres / mysql
So I've also fixed those things
How to review
-------------
1. Check the changes to the docs make sense and that the new wording is clear
1. Manually check that any removed or renamed anchor tags are not in use …
=> Add "amend redis" section and make docs consistent

source/documentation/deploying_services/s3.md
What
----
I don't think this feature needs documenting in depth - it's much more
likely that someone will learn about this through the AWS docs or from
the docs of a library or framework they're using than from our docs.
It still makes sense to mention that we're giving bindings these
permissions though.
alphagov/paas-s3-broker#17 (and the bosh release follow ups) need to go first.
How to review
-------------
* Code review should be enough
Who can review
--------------
=> Document that we give CORS permissions

source/documentation/managing_apps/scaling.md
What
----
A tenant pointed out that this `cf scale` command used a different app name placeholder to the commands above, and it was confusing.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit
=> Use a consistent app name

config/tech-docs.yml
What
----
We are removing the Google Analytics cookies and information relating to the use of Google Analytics whilst the cross gov.uk domain approach is being developed.
How to review
-------------
Code review
Spin up locally and check that no google analytics tracking is enabled.
1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected and check that no google analytics tracking is enabled.
1. Code review
Who can review
--------------
Anyone
=> Remove Google Analytics cookies

source/deploying_apps.html.md.erb, source/documentation/deploying_apps/deploying_dotnet.md, source/documentation/deploying_apps/deploying_java.md
What
----
Sadly the dotnet buildpack is a bit tricky to use because you have to
specify which version of the framework you're using in two places - the
`.csproj` and `buildpack.yml`. This makes the documentation a bit
complicated, but I think this is the best we can do.
How to review
-------------
1. Follow the instructions and check that they (a) make sense and (b) work
1. Review for technical correctness and style
1. Shepherd this through the tech writer two eye process
Who can review
--------------
=> [#170596206] Add documentation for dotnet-core

source/documentation/deploying_services/use_a_custom_domain.erb
What
----
Clarified content in https://docs.cloud.service.gov.uk/deploying_services/use_a_custom_domain/#managing-custom-domains-using-the-cdn-route-service to:
- provide an overview and context of the process
- better explain where a user might have to carry out the various tasks described (ie in DNS provider interface or the PaaS command line)
- link to GOV.UK guidance
How to review
-------------
1. Check the new content fulfils …
=> [#169872495] Review and improve cdn-route service custom domain docs

source/documentation/deploying_apps/buildpacks.md, source/documentation/deploying_apps/deploying_django.md, source/documentation/deploying_apps/deploying_node_js.md, source/documentation/deploying_apps/deploying_rails.md
What
----
Updated sample `manifest.yml` files to replace the singular `buildpack:` with the plural `buildpacks:` and the nested collection. 
The use of `buildpack:` is [deprecated](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#deprecated) in favour of using
```
buildpacks:
- name_of_buildpack
```
Update docs relating to buildpacks, django, rails and node.
How to review
-------------
1. Manually check that the references to `buildpack` in sample `manifest.yml` files have been updated to use `buildpacks` instead. These are found under `/deploying_apps.html` and include …
=> Deprecate the use of buildpack for manifests

source/documentation/deploying_services/route_services.md
What
----
Correct in-page links to "implement a route service". Currently it links to `#implmenting-a-route-service` when it should be `#implement-a-route-service`. This will allow the in page links to work as expected.
How to review
-------------
1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that the two in page links skip to the correct section of the docs
Who can review
--------------
Anyone who isn't Bevan.
=> Correct in-page links to implement a route service

source/documentation/deploying_services/elasticsearch.md
What
----
A tenant asked us about getting Kibana access to their Elasticsearch. We discovered Aiven already provide one. This commit saves the instructions that we gave that tenant so that others can benefit too.
Here's what this content looks like:
> <img width="824" alt="Screenshot 2020-03-04 at 14 34 30" src="https://user-images.githubusercontent.com/163111/75889765-4e60f780-5e25-11ea-8ac0-6baad980ec68.png">
How to review
-------------
Read through the instructions and see if they make sense.
Who can review
--------------
Not @46bit
=> Document the Kibana alongside every Elasticsearch

source/documentation/deploying_apps/deploying_docker_image.md
What
----
Docker images are cached by tag, and reusing a tag can cause errors.
Advises tenants not to do this, and instead to use a unique tag. Suggests what
that tag could be.
How to review
-------------
1. Check you agree with the gist of what's being said
Who can review
--------------
Anyone
=> Docker images are cached by tag, and reusing a tag can cause errors.

source/documentation/deploying_services/postgresql.md, source/documentation/deploying_services/use_a_custom_domain.erb
What
----
* Fix language to make it more inclusive, see https://www.ncsc.gov.uk/blog-post/terminology-its-not-black-and-white I have used safelist to be consistent with  https://github.com/alphagov/paas-ip-authentication-route-service but I don't mind if people prefer the NCSC suggested wording
* Fix previously broken anchor link
How to review
-------------
Run app locally
Anchor link on http://localhost:4567/deploying_services/postgresql/ show work
Who can review
--------------
anyone but me
=> fix link and use more inclusive/accurate language

source/documentation/monitoring_apps/logs.md
What
----
When we did a CF Upgrade, the format of logs shipped via syslog drains changed. The number of bytes of the message is now prepended to each log line.
Additionally, the logs now contain structured data `[tags@12345 key="val" key2="val2]` which contain additional context. We can use `kv` to split these into fields
I applied it to GOV.UK's Coronavirus Logit stack yesterday
How to review
-------------
Use [grokdebug](https://grokdebug.herokuapp.com/) to analyse the following pattern (from the PR) to check that everything parses correctly
grok
```
(%{NONNEGINT:message_length} )?%{SYSLOG5424PRI}%{NONNEGINT:syslog_ver} (?:%{TIMESTAMP_ISO8601:syslog_timestamp}|-) +%{DATA:syslog_host} +%{UUID:cf_app_guid} +\[%{DATA:syslog_proc}\] +- +(\[tags@%{NONNEGINT} …
```
=> Make logstash filters work with syslog agent

source/documentation/getting_started/get_started.erb
Update link text to info about London and Ireland regions to make it clearer to anyone using a screen reader or other assistive technology that these are AWS regions
What
----
Changed the text of several links to include 'regions'
How to review
-------------
2. Check that link text makes sense as part of the sentence and describes the linked content.
Who can review
--------------
Jani
=> Update link text for accessibility

config/tech-docs.yml, source/documentation/deploying_services/elasticsearch.md, source/documentation/deploying_services/use_a_custom_domain.erb, source/documentation/getting_started/get_started.erb
To point them to the new url in PaaS admin
What
----
Update links to the [new support page](https://github.com/alphagov/paas-admin/pull/936)
How to review
-------------
2. Check the links take you to the right place
Who can review
--------------
not @kr8n3r
=> Update support links urls

source/documentation/deploying_services/postgresql.md.erb
[Story](https://www.pivotaltracker.com/story/show/174438274)
What
----
Tell users that they may wish to reconsider using the `public` schema if they care deeply about permissions. Although in practice they shouldn't have to.
Tell users how to use conduit to connect to databases in a read-only fashion.
How to review
-------------
1. …
Who can review
--------------
Not @tlwr
=> [#174438274] Read-only Postgres clarifications

source/documentation/deploying_services/postgresql.md.erb
What
----
Document a current gotcha with read-only bindings
```
kevkeenoy_mhclg Sep 24th at 2:10 PM
Hello... seems like read-only conduits aren't working quite as expected - I opened one to one of our DBs but get...
rdsbroker_d2c440cc_eb3b_4a76_98f3_71b9906644b6=> select * from clients;
ERROR:  permission denied for table clients
tlwr_gds  4 days ago
Hi, yes I’ve seen this happen in other databases
Whenever a view/table/schema gets created (by a non-read-only user) we propagate permissions to the read-only group.
This means if you use a read-only user but permissions haven’t yet been propagated, then it does not have access to the table.
You can either (as a non-read-only user) run
SELECT make_readable_generic()
which is a function we use to allocate permissions
or just
CREATE SCHEMA foo; …
```
=> postgres: guidance on using read-only for old dbs

source/documentation/deploying_services/postgresql.md.erb
[Story](https://www.pivotaltracker.com/story/show/175373731)
What
----
* removed note about manual restore from Postgres docs, this is automated
* add docs about restoring from point in time, consistent with snapshot docs
Related to https://github.com/alphagov/paas-rds-broker/pull/124
How to review
-------------
=> [#175373731] postgres: document how to restore to point in time

source/deploying_services/sqs/index.html.md.erb, source/documentation/deploying_services/index.md, source/documentation/deploying_services/sqs.md
adds docs for using the SQS service
* creating a service, difference between "fifo" and "standard" (and polling for ready)
* updating a service, what options you have to configure it
* how to set up your secondary queue as a dead-letter queue
* binding (and polling for ready)
* unbinding (and polling for ready)
* destroying
=> sqs: service docs

source/documentation/guidance/isolation-segments.md, source/guidance.html.md.erb
What
----
Add initial guidance on using isolation segments, for our initial isolation segment "egress-restricted-1"
We have structured the docs in this slightly elliptical way, because we foresee adding another isolation segment "high-cpu-1" or equivalent soon
_work in progress with @cmcnallygds_
How to review
-------------
=> Add isolation segment section to guidance page

source/documentation/deploying_services/postgresql.md.erb
The 'yourself' here doesn't make sense as both restore methods are now self-service.
What
----
I found the documentation confusing as it implied one method was more self-service than the other.
How to review
-------------
Who can review
--------------
not me
=> remove 'yourself'

source/javascripts/application.js, source/javascripts/cookies.js, source/stylesheets/_cookie-banner.scss, source/stylesheets/screen-old-ie.css.scss, source/stylesheets/screen.css.scss
What
----
Implementation of gtag.js Google analytics and the cookie banner consent model we have on product pages and admin
(alphagov/paas-admin#1123)
As the parent (tech-docs gem) doesn't have a slot for a cookie banner, we're injecting markup with javascript.
The built-in GA tracking options are also not suitable for us, so we're implementing the same tracking we have on our other estates.
It allows users to opt-in or opt-out and not see the banner again for a year
How to review
-------------
- check out branch
- set `cookieDomain` to empty string for localhost test in `source/javascripts/cookies.js`
- preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected.
- if you haven't set a preference you will see a …
=> Implement Google analytics with cookie consent preferences management

source/documentation/deploying_apps/index.erb, source/documentation/deploying_apps/production_checklist.md, source/documentation/getting_started/get_started.erb, source/documentation/managing_apps/ssh.erb
What
----
CF CLI v6 is slowly being deprecated, and is in fact unsupported against the
latest CF API deployment at the time of writing. The only answer is to upgrade
to a supported version of CF CLI v7.
However our docs point people towards installing CF CLI v6, and talk about CF
CLI v7 and version 3 of the API as if they're experimental and maybe not quite
ready yet. This isn't true any more.
This commit makes it clear to tenants that they should be using CF CLI v7 where
at all possible.
How to review
-------------
1. Manually check that any removed or renamed anchor tags are not in use …
=> Drive our tenants towards using CF CLI v7

source/documentation/deploying_apps/index.erb
What
----
Let tenants know that it's not just HTTP they can use with private apps; they can use any TCP-based protocol. Caveat the use of TLS.
How to review
-------------
1. Do you agree with what I've written?
=> Make it clear that private apps can communicate over TCP generally

source/documentation/deploying_services/postgresql.md.erb
What
----
Changed flag in documentation.
Current instructions lead to "Incorrect Usage: unknown flag `s'"
Have tested with `-e` (as per `--help`) and this seems to do what the documentation intended.
```
OPTIONS:
-e              Show plan details for a particular service offering
-b              Only show details for a particular service broker
--no-plans      Hide plan information for service offering
```
How to review
-------------
1. Double-check the new flag is what was intended in the documentation.
Who can review
--------------
Anyone who familiar with the PaaS!
=> Fix flag used in `cf marketplace` example

source/documentation/deploying_services/postgresql.md.erb
What
----
See https://github.com/alphagov/paas-cf/pull/2583 
How to review
-------------
Check that there's nowhere else in the docs that suggests `postgis` is enabled by default
Who can review
--------------
Claire McNally, and one other
=> [#176574936] `postgis` is no longer enabled by default for any version of Postgres

source/documentation/deploying_services/postgresql.md.erb, source/documentation/managing_apps/ssh.erb
What
----
We no longer offer Postgres 9.5 instances, so our documentation shouldn't mention them.
How to review
-------------
1. See if I missed any references
=> [#177267449] Remove references to Postgres 9.5

source/javascripts/cookies.js
What
----
In https://www.pivotaltracker.com/n/projects/1275640/stories/177950343 PA reported that pages with hashes in urls, like
https://docs.cloud.service.gov.uk/deploying_services/sqs/#remove-the-service were not showing up in GA.
This was because we weren't sending a modified string to pageview that included the location.hash.
This PR fixes that by concatenating pathname and hash strings.
How to review
-------------
- review code
- fix also deployed to https://paas-docs-fix.london.cloudapps.digital/
PA will be checking that data received is as expected
Who can review
--------------
not @kr8n3r
=> Include location.hash in GA pageview

.github/workflows/pr-tests.yml, .gitignore, package-lock.json, package.json, source/javascripts/cookies.js
What
----
Our style of choice is StandardJS. Though there's not much JS here, it should be Standard.
How to review
-------------
1. The tech docs should still build and look the same.
2. `npm install && npm test` should succeed.
Who can review
--------------
Any devs
=> Add StandardJS linting workflow

source/documentation/deploying_apps/deploying_django.md
What
----
Updated the Django app deploy instructions to work with up-to-date `whitenoise` package.
Since version 4.0.0, that package has not required editing of the `wsgi.py` module. Its functionality has instead been made available inside the Django project by including it as middleware in the `settings.py` module.
=> Use up-to-date whitenoise and waitress packages

Staticfile, source/errors/404.html.md.erb, source/errors/generic.html.md.erb, source/javascripts/application.js, source/javascripts/cookies.js, source/javascripts/event-tracking.js
What
----
Send interaction events to GA if the user has consented to analytics cookies.
As we cannot add data tracking attributes to targeted elements, all of the targeting logic is done as part of the script.
This adds logic to determine when the following elements are interacted with:
- top level navigation
- external links
- anchor links (links with #)
- search
- sidebar navigation (table of contents):
- top level item
- sub level item
- toggle collapse/expand button
Additionally, we send events for 404 and 500 pages.
Follows on from https://github.com/alphagov/paas-product-pages/pull/120 and https://github.com/alphagov/paas-admin/pull/1423
How to review
-------------
- run locally or visit https://paas-tech-docs-ga-test.london.cloudapps.digital/
- if you have Omnibug extension, you …
=> Implement GA event tracking

source/javascripts/event-tracking.js
What
----
Consolidate 2 events into one as per https://www.pivotaltracker.com/n/projects/1275640/stories/178674295
How to review
-------------
- see https://paas-tech-docs-search-event.london.cloudapps.digital/ 
or run locally (update `cookieDomain` in cookies.js to empty string
- accept cookies
- use Omnibug chrome extension to test
Who can review
--------------
anyone
=> Update search GA event

source/documentation/monitoring_apps/logs.md
What
----
The Logstash filter code is now found under Logstash Pipelines within Logit.
This updates the documentation to reflect this change.
How to review
-------------
Log into Logit and confirm this is the correct place to find the Logstash Filters
=> Update logstash filter docs

config/tech-docs.yml
What
----
Tech docs template allows for a [`full_service_name`](https://tdt-documentation.london.cloudapps.digital/configure_project/global_configuration/#full-service-name)
that gets used in the title. We keep the `service_name` for use in the header, as header comes with the GOV.UK logo already
Before
After
How to review
-------------
Who can review
--------------
not @kr8n3r
=> Use full service name in the `title`

Staticfile, nginx/conf/includes/custom_headers.conf
as per https://github.com/alphagov/govuk-rfcs/pull/142
What
----
Added Staticfile directive to hopefully inject `nginx/conf/includes/custom_headers.conf` into the main `location` section of the generated nginx conf.
See https://docs.cloudfoundry.org/buildpacks/staticfile/index.html#staticfile for documentation on this
Is the `redirect/nginx.conf` file in here actually used at all? If not might we be able to remove it because it's pretty confusing..
How to review
-------------
See test app pushed to https://paas-tech-docs-ris.cloudapps.digital, observe headers served.
=> [#178671156] add Permissions-Policy header

Dockerfile, source/audit_events.html.md.erb, source/documentation/audit_events/accessing_audit_events.md
What
----
Add a section to the tech docs to describe what audit events are, how to access them via the web interface, how to access them via the API
- story [#169616393](https://www.pivotaltracker.com/n/projects/1275640/stories/169616393)
How to review
-------------
Who can review
--------------
- not @pauldougan 
- @LeePorte 
=> add new section on paas audit events

source/documentation/deploying_services/index.md
Colin from DfE reported a broken link in our documentation
What
----
link to IA page is broken following from restructuring of content
Describe what you have changed and why.
new link
How to review
-------------
1. …
Who can review
--------------
anyone but @pauldougan
=> Correct broken link to information-assurance

Dockerfile
What
----
Because each line of a dockerfile can hypothetically be executed a billion years apart, it's important to run all apt updates at exactly the same time as their installs, otherwise your index will be out of date by more than all of recorded history. 
How to review
-------------
``` sh
$ docker build .
```
Who can review
--------------
Non-Cornish PaaS devs
=> in-lined apt updates and install

Gemfile.lock, source/accessibility.html.md.erb
What
----
- update the tech-docs-gem to version 2.4.2 which [brings in accessibility fixes](https://github.com/alphagov/tech-docs-gem/blob/master/CHANGELOG.md)
- update the change date when we did the last change in #390 and update review date to todays date
How to review
-------------
- run local to check app works
Who can review
--------------
not @kr8n3r
=> Make docs more accessible

source/documentation/guidance/static-egress-ips.md, source/documentation/monitoring_apps/logs.md, source/guidance.html.md.erb
What
----
Signpost links to paas-admin pages where ip addresses are viewable
Why here? because users search our documentation, but we don't want them to be easily publicly available.
How to review
-------------
Who can review
--------------
not @kr8n3r
=> Add section on static IP addresses

source/documentation/managing_apps/redirect_all_traffic.md
What
----
"You can read more about nginx customisation" on https://docs.cloud.service.gov.uk/managing_apps.html#redirecting-all-traffic
was  pointing to the StaticBuildpack.
This changes the link to point to nginx buildpack documentation
How to review
-------------
1. …
Who can review
--------------
not @kr8n3r
=> Fix outdated link

source/documentation/deploying_services/elasticsearch.md, source/documentation/deploying_services/mysql.md, source/documentation/deploying_services/redis.md
What
----
The `-s` flag was correct in CF CLI v6, but changed to `-e` in
CF CLI v7.
=> Correct flag used in CF marketplace command

source/documentation/deploying_services/mysql.md, source/documentation/deploying_services/postgresql.md.erb
What
----
Previously, the sentence suggested this was true only for free
plans. However, this isn't quite true, because we don't begin
backing up those plans once a tenant begins paying for it.
To explain: free plans are only free to trial organisations.
Once an organisation exits the trial period, they pay for
everything they use.
How to review
-------------
1. …
Who can review
--------------
Describe who can review the changes. Or more importantly, list the …
=> [#180028025] Clarify that unencrypted database plans are not backed up

source/deploying_services/opensearch/index.html.md.erb, source/documentation/deploying_services/index.md, source/documentation/deploying_services/opensearch.md, source/documentation/monitoring_services/metrics.md
What
----
We are making OpenSearch available to tenants, but we need some docs so that they know how to use it 🤓 
My assumptions:
- backups work similarly to how they do for elasticsearch
- we export OpenSearch metrics on request (as we do for elasticsearch)
- I don't need to add a [compatibility note for elasticsearch-py](https://github.com/alphagov/paas-tech-docs/blob/07648983d408de2029d9db5a9996b14df9b124a2/source/documentation/deploying_services/elasticsearch.md#compatibility-notes)
How to review
-------------
2. Read the docs,  make sure they make sense
3. Check I haven't missed adding OpenSearch …
=> Update docs to include OpenSearch

source/documentation/deploying_services/opensearch.md
https://www.pivotaltracker.com/story/show/180810438
What
----
Turns out you don't use the service name for restoring OS instances, you use the GUID. Really, we should probably flesh this out to be more like (a clone of?) the instructions we use for postgres, where we include details of how to discover a service's guid - but right now I just want to get these words switched to prevent this from being wrong.
How to review
-------------
1. …
Who can review …
=> opensearch restore: `restore_from_latest_backup_of` expects a guid

source/documentation/deploying_services/use_a_custom_domain.erb
What
----
Updates docs to show how to use `cf service SERVICE_INSTANCE`
How to review
-------------
1. …
Who can review
--------------
Anyone
@AP-Hunt  and @cmcnallygds please
=> Adds alternative option for getting instance information

source/documentation/using_ci/github_actions.md
What
----
We weren't installing CloudFoundry CLI quite right in our GitHub Actions
documentation. It wasn't copying all the right files, because `cf` was a
symlink to `./cf7` and we weren't copying that.
How to review
-------------
Take a look [at the result of the last run on my test branch](https://github.com/alphagov/paas-tech-docs/runs/4969504850?check_suite_focus=true). I've deleted the branch (d'oh), but the logs show what commands were being run. You can see they work and match what's in this PR.
=> Correctly install CF in GitHub Actions documentation

source/documentation/deploying_services/redis.md, source/documentation/deploying_services/redis.md.erb
What
----
Update the docs on upgrading Redis instances. Our ElastiCache broker does not currently support `update-service` to upgrade Redis plans. Including step-by-step instructions to work around this (thanks @AP-Hunt).
How to review
-------------
1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected. The internal path to the change is `/deploying_services/redis/#upgrade-redis-service-plan`.
Who can review
--------------
Not @schmie
=> Update the docs on upgrading Redis instances

source/documentation/monitoring_apps/logs.md
What
----
Following https://www.pivotaltracker.com/story/show/181201741
Added paragraph clarifying what severity level information to expect from the example logstash configuration we provide. Otherwise people may be confused when they don't get their full gamut of log levels represented in their ELK stack.
How to review
-------------
1. …
Who can review
--------------
Anyone but @risicle though hopefully someone with a content eye.
=> logit/logstash filters: add paragraph on severity levels to expect

requirements.txt
What
----
`pip install -r requirements.txt` is encountering a fatal error when attempting to clone the linkchecker repo using the unencrypted git protocol.
This is because this functionality has been deprecated ([link](https://github.blog/2021-09-01-improving-git-protocol-security-github/)).
How to review
-------------
- Make sure the "Run pip install --user -r requirements.txt" step in the GitHub Actions "Run tests" job is passing.
- Think of any reason why we should use SSH instead of HTTPS, here - given that is was unauthenticated and unencrypted before, I think this is unnessecary.
Who can review
--------------
not @schmie
=> Switch git protocol for linkchecker repo to https

source/documentation/deploying_services/mysql.md
What
----
See https://govuk.zendesk.com/agent/tickets/5000660
Figuring out the exact combinations of server/client versions that need these and communicating that here would be too much. This at least points people in the right direction.
How to review
-------------
1. …
Who can review
--------------
Not @risicle
=> mysql paas/paas backup: note `mysqldump` flags that might be needed on newer versions

Gemfile.lock
What
----
Update commonmarker from 0.23.5 to 0.23.6 to address [CVE](https://github.com/alphagov/paas-tech-docs/security/dependabot/14)
=> Update commonmarker  from 0.23.5 to 0.23.6

source/documentation/guidance/migration.md, source/documentation/guidance/pentest.md, source/documentation/index.md, source/guidance.html.md.erb
What
----
Add pointers to migration guidance to take user to the actual guidance that will reside on the product pages at https://cloud.service.gov.uk/migration-guidance 
> this is blocked by https://www.pivotaltracker.com/n/projects/1275640/stories/183626154 
which is the story to deploy the actual guidance to the product pages, do not merge this pr until this story is played. 
How to review
-------------
Who can review
--------------
anyone but @pauldougan
=> add pointers to the migration guide to home page and guidance section

source/documentation/deploying_services/mysql.md, source/documentation/deploying_services/postgresql.md.erb
What
----
Our snapshot retention period is 35 days. We thought we had changed it to 7, but as it turns out we had not.
Context from AP-hunt digging into things:
> 1. We set the final snapshot retention period to 35 days in March 2018 and have never revisited it
> 2. The automated snapshot retention period is configured at the plan level, because ..
> 3. In September 2016 we marked the tests for user configurability of  backup retention as Pending in the test suite, and have never revisited it. At the time, the relevant code looked like
>     
>         if provisionParameters.BackupRetentionPeriod > 0 {
>             dbInstanceDetails.BackupRetentionPeriod = provisionParameters.BackupRetentionPeriod
>         }
>     
> 4. In September 2018 we did some refactoring and replaced the above …
=> Update retention snapshot period to match reality

source/documentation/deploying_apps/index.erb, source/documentation/deploying_apps/stopping_and_deleting_apps.md.erb, source/documentation/deploying_services/configure_cdn.md, source/documentation/deploying_services/redis.md.erb, source/documentation/deploying_services/use_a_custom_domain.erb, source/documentation/managing_apps/quotas.md, source/documentation/monitoring_apps/metrics.md
What
----
We're using cf cli v8 so the examples in our docs should use the same version. 
I've gone through all the examples in the docs to check if any of the command differences from the [cf cli v7](https://docs.cloudfoundry.org/cf-cli/v7.html#differences) and [cf cli v8](https://docs.cloudfoundry.org/cf-cli/v8.html#differences) were relevant.
The removal of the `--hostname` flag also required a change in the [paas-prometheus-exporter](https://github.com/alphagov/paas-prometheus-exporter/pull/47)
How to review
-------------
1. do the changes make sense? in particular the `--hostname` flag one
1. Manually check that any removed or renamed anchor tags …
=> Update to cf v8

.github/workflows/pr-tests.yml
What
----
Upgrade this GitHub workflow to ~20.04~ 22.04, ubuntu 18.04 being now deprecated and this preventing the workflow from running in e.g. https://github.com/alphagov/paas-tech-docs/pull/476
How to review
-------------
:eyes:
=> pr-tests workflow: upgrade to ubuntu-22.04 base

source/documentation/deploying_services/route_services.md
What
----
https://www.pivotaltracker.com/story/show/180890489
Thinking about this more, if we were in other circumstances the thing to do here would probably be to just add a script to the `paas-ip-authentication-route-service` repo that would scrape and insert/update the appropriate IPs for them.
How to review
-------------
1. …
=> route_services: add caveat about using ip-restriction service with CDNs

source/documentation/deploying_services/use_a_custom_domain.erb
What
----
https://www.pivotaltracker.com/story/show/183923174
Lifted `--params` cli invocation wording directly from redis section.
Added distribution id information as a simple note to an existing question/section rather than a whole new question/section that could get us bogged down in detail for something that's quite obscure.
=> cdn-route services: add note on cloudfront distribution id retrieval, use `--params` argument to retrieve instance config

source/documentation/deploying_services/mysql.md, source/documentation/deploying_services/postgresql.md.erb, source/documentation/deploying_services/redis.md.erb
What
----
Related to https://www.pivotaltracker.com/story/show/183510470, we need to document this if we want to point tenants towards it in communication.
Largely cribbed from mysql section.
Incidentally, update mysql and postgresql section's final sentences, which previously implied tenants just had to make sure it worked when manually triggered, which is kinda missing the point.
How to review
-------------
1. …
=> redis: document `test_failover` feature

.github/workflows/pr-tests.yml
Description:
-------------
- Currently we pin to versions which means that we automatically pull in the latest changes which presents a security risk as we don't know which code is running in our build pipeline.
- This PR fixes this by pinning to a specific hash
- A future PR will configure dependabot to raise PR's automatically for later versions of GitHub Actions against their hashes
How to review
-------------
Code review
Who can review
--------------
=> 185509385 - Pin GitHub Actions to specific hashes

.github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml
Description:
-------------
- Dependabot will raise a PR for GitHub actions with a hash for the newer version
- Currently set to weekly to follow the current practice but this can be changed later pending an RFC
How to review
-------------
Code review
Who can review
--------------
=> 185509385 - Configure dependabot to track GitHub actions

source/documentation/deploying_services/mysql.md, source/documentation/deploying_services/postgresql.md.erb
Backups are held for 7 days and final snapshots are held for 35 days. Update the docs to reflect this reality.
=> Fix retention days for backups

.github/workflows/deploy.yml, .github/workflows/pr-tests.yml
Description:
----
- Pipeline runs the tests first to ensure they pass before deploying anything
- Concurrency group is named as 'pages' and has cancel-in-progress: false. This is because rather than having some deployments in a queue cancelled have them queue up and complete in an orderly fashion.
How to review
-------------
Code review and review comments in the story.
Who can review
--------------
Anyone but @nimalank7
=> 185550872 - Create pipeline to deploy to Github pages

.github/workflows/deploy.yml
Description:
-------------
- Slack notification message on failure was previously empty as the event that triggers the workflow is no longer pull requests but merging into main
- The message now posts the commit SHA when a deployment fails
How to review
-------------
Code review
=> 185550872 - Fix Slack notification message

source/documentation/deploying_services/mysql.md, source/documentation/deploying_services/postgresql.md.erb
What
----
As per ticket 185551147, we move the documentation for database restores from a specific point-in-time snapshot to a more relevant place.
How to review
-------------
2. Manually check that any removed or renamed anchor tags are not in use ([linkchecker](https://github.com/linkcheck/linkchecker) doesn't do this).
3. …
Who can review
--------------
Anyone but @fearoffish
=> move documentation for point-in-time restores

.github/workflows/deploy.yml
Description:
---
- Incorrectly uses `bundle exec middleman build` and not `make build`
- Change allows `googlec7239f490e1990a5.html` to be copied into the directory
=> BAU - Use make build step in deploy.yml

Makefile, config.rb, security.txt.html
Description:
----
- Both the `security.txt` and `.well-known/security.txt` display as `.txt` files in GitHub pages not as HTML. There isn't a known way to change the MIME type to text/html in GitHub pages so the workaround involves copying the `security.txt.html` file manually
- The redirect is added for middleman server
- The empty `.nojekyll` file is added to turn off Jekyll in GitHub pages as this causes it not to recognize directories starting with . - see [here](https://github.com/orgs/community/discussions/22227)
=> BAU - Fix issue with security.txt not displaying as HTML

source/documentation/deploying_services/s3.md
What
----
The recently added s3 migration guidance had a link within it that was faulty. The link is named `create a service key and get the service key credentials`. That has been corrected.
How to review
-------------
1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that the link named `create a service key and get the service key credentials` works as expected.
Who can review
--------------
Any paas developer..
=> [#1275640] Corrected a link in s3 Migration guidance
